include:
  package:lint/analysis_options.yaml

linter:
  rules:
    - parameter_assignments
    - prefer_expression_function_bodies
    - require_trailing_commas
    - unnecessary_lambdas

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "lib/injection.config.dart"
    - "test"
  errors:
    missing_return: error
    missing_required_param: error
    parameter_assignments: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore