name: worldon
description: Front end of the World On project.

publish_to: 'none'

# Basic base ten increases
# Last number increases by 1 until it reaches 9
# Then it goes back to 0 and it's neighbour to the left increases by 1
# The number after the + always increases by 1
# Usually both numbers should increase by 1 at the same time
# For example 1.1.7+17 => 1.1.8+18
version: 1.2.0+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  algolia: ^1.0.1
  animated_bottom_navigation_bar: ^0.3.2
  another_flushbar: ^1.10.20
  auto_route: ^2.2.0
  auto_size_text: ^3.0.0-nullsafety.0
  bloc_test: ^8.0.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  cloud_firestore: ^1.0.7
  dartz: ^0.10.0-nullsafety.1
  email_validator: ^2.0.1
  equatable: ^2.0.0
  firebase_auth: ^1.1.3
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.16.0
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^3.0.5
  flutter_vector_icons: ^1.0.0
  freezed: ^0.14.1+3
  freezed_annotation: ^0.14.1
  geoflutterfire: ^3.0.0-nullsafety.2
  geolocator: ^7.0.3
  get_it: ^7.1.3
  google_maps_flutter:
  google_sign_in: ^5.0.2
  image_picker: ^0.7.4
  implicitly_animated_reorderable_list: ^0.4.0-dev+2
  in_app_purchase: ^0.5.2
  injectable: ^1.4.0
  intl: ^0.17.0
  jiffy: ^4.1.0
  json_annotation: ^4.0.1
  kt_dart: ^0.9.0
  logger: ^1.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  multi_image_picker: ^4.8.0
  number_display: ^3.0.0
  path_provider: ^2.0.1
  percent_indicator: ^3.0.1
  permission_handler: ^7.1.0
  provider: ^5.0.0
  quiver: ^3.0.1
  rxdart: ^0.26.0
  social_share: ^2.1.1
  uuid: ^3.0.4
  visibility_detector: ^0.2.0

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^9.0.0
  injectable_generator: ^1.4.0
  json_serializable: ^4.1.1
  lint: ^1.5.3
  mockito: ^5.0.7

flutter_icons:
  image_path: "assets/world_on_logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: MovingSkate
      fonts:
        - asset: fonts/Moving-Skate.ttf

flutter_intl:
  main_locale: en_US
  enabled: true
