name: worldon
description: Front end of the World On project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^5.0.6
  # For dependency injection
  injectable: ^1.0.7
  # Bloc for state management
  flutter_bloc: ^6.1.1
  # Value equality
  # Probably useless now
  equatable: ^1.2.5
  # Functional programming thingies
  dartz: ^0.9.2
  # For unions generation
  freezed_annotation: ^0.12.0
  # For email validation
  email_validator: ^1.0.6
  # For getting the geolocation of the user
  geolocator: ^6.1.14
  # For Kotlin like collections
  kt_dart: ^0.8.0
  # For easier bloc testing
  bloc_test: ^7.1.0
  # For ease of serialization
  json_annotation: ^3.1.1
  # For ease of routing
  auto_route: ^0.6.9
  # For ease of showing status bars
  flushbar: ^1.10.4
  # For dynamically resizing text
  auto_size_text: ^2.1.0
  # For showing the user's experience progression
  percent_indicator: ^2.1.9
  # Takes out some boilerplate
  flutter_hooks: ^0.15.0
  # For FloatingActionButton menus
  unicorndial: ^1.1.5
  # To add shadow to icons with less boiler plate
  icon_shadow: ^1.0.1
  # For getting images from the device
  image_picker: ^0.6.7+22
  # For getting multiple images from the device
  multi_image_picker: ^4.7.14
  # Local database, mostly for back-end simulation
  moor_flutter: ^3.1.0
  moor: ^3.4.0
  # For viewing the database
  moor_db_viewer: ^2.0.3
  # For providing objects down the widget tree
  provider: ^4.3.3
  # For environment control
  flutter_dotenv: ^3.1.0
  # For ease of logging
  logger: ^0.9.4
  # For better stream control
  rxdart: ^0.25.0
  # For the experience image gallery
  carousel_slider: ^3.0.0
  # Unique IDs for entities
  uuid: ^2.2.2
  # For Signing in and registering with Google
  google_sign_in: ^4.5.9
  # For use with Firebase as backend
  firebase_core: ^0.7.0
  # For authentication with Firebase
  firebase_auth: ^0.20.0+1
  # For simple data storage
  cloud_firestore: ^0.16.0
  # For complex data storage (images)
  firebase_storage: ^7.0.0
  # For drawing routes in the map
  google_map_polyline:
  # For mapping
  google_maps_flutter:
  # For localization
  intl: 0.16.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # For mocking dependencies during unit testing
  mockito: ^4.1.2
  # For unions generation
  freezed: ^0.12.7
  # Collection of lint rules
  lint: ^1.3.0
  # For dependency injection code generation
  injectable_generator: ^1.0.7
  # For Serializing entities to JSON
  json_serializable: ^3.5.1
  # For auto generating the routes
  auto_route_generator: ^0.6.10
  # For ease of setting the app icon
  flutter_launcher_icons: ^0.8.1
  # For extra icons
  font_awesome_flutter: ^8.11.0
  # Generator for moor
  moor_generator: ^3.4.1
  # For testing with moor
  moor_ffi: ^0.8.0
  build_runner:

flutter_icons:
  image_path: "assets/world_on_logo.jpg"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  main_locale: en_US
  enabled: true
