name: worldon
description: Front end of the World On project.

publish_to: 'none'

# Basic base ten increases
# Last number increases by 1 until it reaches 9
# Then it goes back to 0 and it's neighbour to the left increases by 1
# The number after the + always increases by 1
# Usually both numbers should increase by 1 at the same time
# For example 1.1.7+17 => 1.1.8+18
version: 1.2.4+24

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  algolia: ^1.0.1
  animated_bottom_navigation_bar: ^0.3.2
  another_flushbar: ^1.10.22
  auth_buttons: ^1.0.1+3
  auto_route: ^2.2.0
  auto_size_text: ^3.0.0-nullsafety.0
  bloc_test: ^8.0.1
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  cloud_firestore: ^1.0.7
  cloud_functions: ^1.1.0
  dartz: ^0.10.0-nullsafety.1
  email_validator: ^2.0.1
  equatable: ^2.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_storage: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_carousel_slider: ^1.0.8
  flutter_hooks: ^0.17.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^0.6.0
  flutter_speed_dial: ^3.0.5
  flutter_vector_icons: ^1.0.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  geoflutterfire: ^3.0.0-nullsafety.2
  geolocator: ^7.0.3
  get_it: ^7.1.3
  google_maps_flutter:
  google_sign_in: ^5.0.4
  image_picker: ^0.7.5+3
  implicitly_animated_reorderable_list: ^0.4.0-dev+2
  in_app_purchase: ^1.0.1
  injectable: ^1.4.1
  intl: ^0.17.0
  jiffy: ^4.1.0
  json_annotation: ^4.0.1
  kt_dart: ^0.9.1
  logger: ^1.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  multi_image_picker: ^4.8.1
  number_display: ^3.0.0
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
  permission_handler: ^8.0.0+2
  provider: ^5.0.0
  quiver: ^3.0.1
  rxdart: ^0.26.0
  simple_animations: ^3.1.1
  social_share: ^2.1.1
  uuid: ^3.0.4
  visibility_detector: ^0.2.0

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^9.0.0
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  lint: ^1.5.3
  mockito: ^5.0.9

flutter_icons:
  image_path: "assets/world_on_logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: MovingSkate
      fonts:
        - asset: fonts/Moving-Skate.ttf
    - family: Geometria
      fonts:
        - asset: fonts/Geometria.ttf
        - asset: fonts/Geometria-Bold.ttf
          weight: 700
        - asset: fonts/Geometria-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Geometria-ExtraBold.ttf
          weight: 800
        - asset: fonts/Geometria-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Geometria-ExtraLight.ttf
          weight: 200
        - asset: fonts/Geometria-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Geometria-Heavy.ttf
          weight: 900
        - asset: fonts/Geometria-HeavyItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Geometria-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Geometria-Light.ttf
          weight: 300
        - asset: fonts/Geometria-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Geometria-Medium.ttf
          weight: 500
        - asset: fonts/Geometria-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Geometria-Thin.ttf
          weight: 100
        - asset: fonts/Geometria-ThinItalic.ttf
          weight: 100
          style: italic


flutter_intl:
  main_locale: en_US
  enabled: true
