name: worldon
description: Front end of the World On project.

publish_to: 'none'

# Basic base ten increases
# Last number increases by 1 until it reaches 9
# Then it goes back to 0 and it's neighbour to the left increases by 1
# The number after the + always increases by 1
# Usually both numbers should increase by 1 at the same time
# For example 1.1.8+18 => 1.1.9+19 => 1.2.0+20
version: 1.4.0+40

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  algolia: ^1.1.1
  animated_bottom_navigation_bar: ^1.1.0
  another_flushbar: ^1.10.29
  auth_buttons: ^3.0.0
  auto_route: ^5.0.1
  auto_size_text: ^3.0.0
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.2.0
  cloud_functions: ^4.0.6
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_analytics: ^10.0.7
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  firebase_storage: ^11.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_carousel_slider: ^1.0.9
  flutter_hooks: ^0.18.5+1
  flutter_local_notifications: ^12.0.4
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_speed_dial: ^6.0.0
  flutter_vector_icons: ^2.0.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  geoflutterfire2: ^2.3.12
  geolocator: ^9.0.1
  get_it: ^7.2.0
  google_maps_flutter:
  google_sign_in: ^5.4.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  implicitly_animated_reorderable_list: ^0.4.2
  in_app_purchase: ^3.0.7
  in_app_purchase_android: ^0.2.3+3
  injectable: ^2.1.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.6.0
  kt_dart: ^1.0.0
  logger: ^1.1.0
  material_design_icons_flutter: ^6.0.7096
  meta: ^1.7.0
  mockito: ^5.3.0
  multi_image_picker2: ^5.0.2
  number_display: ^3.0.0
  path: ^1.8.1
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  permission_handler: ^10.0.0
  provider: ^6.0.3
  quiver: ^3.1.0
  rxdart: ^0.27.5
  sa3_liquid: ^1.0.1
  showcaseview: ^2.0.0+1
  simple_animations: ^5.0.0+2
  social_share: ^2.2.1
  uuid: ^3.0.6
  visibility_detector: ^0.3.3

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.3.1
  lint: ^2.0.1

flutter_icons:
  image_path: "assets/logo/world_on_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
  fonts:
    - family: MovingSkate
      fonts:
        - asset: fonts/Moving-Skate.ttf
    - family: Geometria
      fonts:
        - asset: fonts/Geometria.ttf
        - asset: fonts/Geometria-Bold.ttf
          weight: 700
        - asset: fonts/Geometria-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Geometria-ExtraBold.ttf
          weight: 800
        - asset: fonts/Geometria-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Geometria-ExtraLight.ttf
          weight: 200
        - asset: fonts/Geometria-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Geometria-Heavy.ttf
          weight: 900
        - asset: fonts/Geometria-HeavyItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Geometria-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Geometria-Light.ttf
          weight: 300
        - asset: fonts/Geometria-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Geometria-Medium.ttf
          weight: 500
        - asset: fonts/Geometria-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Geometria-Thin.ttf
          weight: 100
        - asset: fonts/Geometria-ThinItalic.ttf
          weight: 100
          style: italic


flutter_intl:
  main_locale: en_US
  enabled: true
