// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

import 'package:cloud_firestore/cloud_firestore.dart' as _i84;
import 'package:firebase_auth/firebase_auth.dart' as _i83;
import 'package:get_it/get_it.dart' as _i1;
import 'package:google_sign_in/google_sign_in.dart' as _i99;
import 'package:injectable/injectable.dart' as _i2;

import 'application/achievement_management/achievement_management_actor/achievement_management_actor_bloc.dart' as _i3;
import 'application/achievement_management/achievement_management_form/achievement_management_form_bloc.dart' as _i4;
import 'application/achievement_management/achievement_management_watcher/achievement_management_watcher_bloc.dart' as _i5;
import 'application/authentication/authentication/authentication_bloc.dart' as _i14;
import 'application/authentication/log_in_form/log_in_form_bloc.dart' as _i110;
import 'application/authentication/registration_form/registration_form_bloc.dart' as _i147;
import 'application/comments/comment_actor/comment_actor_bloc.dart' as _i29;
import 'application/comments/comment_form/comment_form_bloc.dart' as _i30;
import 'application/comments/comment_watcher/comment_watcher_bloc.dart' as _i34;
import 'application/core/experience_card_actor/experience_card_actor_bloc.dart' as _i63;
import 'application/core/experience_card_like_check/experience_card_like_check_bloc.dart' as _i64;
import 'application/core/user_profile_button_watcher_bloc.dart' as _i189;
import 'application/experience_log/experience_log_actor/experience_log_actor_bloc.dart' as _i68;
import 'application/experience_log/experience_log_watcher/experience_log_watcher_bloc.dart' as _i72;
import 'application/experience_management/experience_editing_form/experience_editing_form_bloc.dart' as _i65;
import 'application/experience_management/experience_management_actor/experience_management_actor_bloc.dart' as _i73;
import 'application/experience_management/experience_management_form/experience_management_form_bloc.dart' as _i74;
import 'application/experience_management/objective_form/objective_form_bloc.dart' as _i128;
import 'application/experience_management/objectives_creation/objectives_creation_bloc.dart' as _i129;
import 'application/experience_management/reward_form/reward_form_bloc.dart' as _i153;
import 'application/experience_management/rewards_creation/rewards_creation_bloc.dart' as _i155;
import 'application/experience_navigation/experience_finish_actor/experience_finish_actor_bloc.dart' as _i66;
import 'application/experience_navigation/experience_like_actor/experience_like_actor_bloc.dart' as _i67;
import 'application/experience_navigation/experience_navigation_watcher/experience_navigation_watcher_bloc.dart' as _i81;
import 'application/experience_navigation/map_controller/map_controller_bloc.dart' as _i118;
import 'application/experience_navigation/objectives_tracker/objectives_tracker_bloc.dart' as _i130;
import 'application/experience_navigation/rate_experience_difficulty_actor/rate_experience_difficulty_actor_bloc.dart' as _i144;
import 'application/experience_navigation/recommended_experiences_watcher/recommended_experiences_watcher_bloc.dart' as _i145;
import 'application/main_feed/main_feed_watcher/main_feed_watcher_bloc.dart' as _i117;
import 'application/navigation/navigation_actor/navigation_actor_bloc.dart' as _i119;
import 'application/notifications/new_notifications_watcher/new_notifications_watcher_bloc.dart' as _i120;
import 'application/notifications/notification_actor/notification_actor_bloc.dart' as _i122;
import 'application/notifications/notifications_watcher/notifications_watcher_bloc.dart' as _i127;
import 'application/options/options_form/options_form_bloc.dart' as _i131;
import 'application/options/user_actor/user_actor_bloc.dart' as _i188;
import 'application/profile/block_actor/block_actor_bloc.dart' as _i20;
import 'application/profile/blocked_watcher/blocked_watcher_bloc.dart' as _i23;
import 'application/profile/follow_actor/follow_actor_bloc.dart' as _i85;
import 'application/profile/profile_achievements_watcher/profile_achievements_watcher_bloc.dart' as _i133;
import 'application/profile/profile_editing_form/profile_editing_form_bloc.dart' as _i134;
import 'application/profile/profile_experiences_watcher/profile_experiences_watcher_bloc.dart' as _i135;
import 'application/profile/profile_interests_watcher/profile_interests_watcher_bloc.dart' as _i136;
import 'application/profile/profile_users_watcher/profile_users_watcher_bloc.dart' as _i141;
import 'application/profile/profile_watcher/profile_watcher_bloc.dart' as _i142;
import 'application/search/search_by_name_form/search_by_name_form_bloc.dart' as _i157;
import 'application/search/search_experiences_by_difficulty/search_experiences_by_difficulty_bloc.dart' as _i158;
import 'application/search/search_experiences_by_name_watcher/search_experiences_by_name_watcher_bloc.dart' as _i159;
import 'application/search/search_experiences_by_tags/search_experiences_by_tags_bloc.dart' as _i160;
import 'application/search/search_tags_by_name_watcher/search_tags_by_name_watcher_bloc.dart' as _i165;
import 'application/search/search_users_by_name_watcher/search_users_by_name_watcher_bloc.dart' as _i166;
import 'application/search/tag_selector/tag_selector_bloc.dart' as _i185;
import 'application/store/buy_coins/buy_coins_bloc.dart' as _i24;
import 'application/store/buy_item/buy_item_bloc.dart' as _i25;
import 'application/store/load_user/load_user_bloc.dart' as _i104;
import 'application/store/purchasable_items_watcher/watch_purchasable_items_bloc.dart' as _i205;
import 'application/store/store_navigation_actor/store_navigation_actor_bloc.dart' as _i168;
import 'application/tag_management/tag_card_actor/tag_card_actor_bloc.dart' as _i173;
import 'application/tag_management/tag_management_actor/tag_management_actor_bloc.dart' as _i178;
import 'application/tag_management/tag_management_form/tag_management_form_bloc.dart' as _i179;
import 'application/tag_management/tag_management_watcher/tag_management_watcher_bloc.dart' as _i184;
import 'data/achievement_management/repository/development_achievement_repository.dart' as _i8;
import 'data/achievement_management/repository/production_achievement_repository.dart' as _i9;
import 'data/authentication/repository/development_authentication_repository.dart' as _i16;
import 'data/authentication/repository/production_authentication_repository.dart' as _i219;
import 'data/comments/repository/development_comment_repository.dart' as _i33;
import 'data/comments/repository/production_comment_repository.dart' as _i222;
import 'data/core/misc/cloud_storage/cloud_storage_service.dart' as _i28;
import 'data/core/modules/firebase_injectable_module.dart' as _i226;
import 'data/core/repository/development_core_repository.dart' as _i37;
import 'data/core/repository/development_geo_location_repository.dart' as _i89;
import 'data/core/repository/production_core_repository.dart' as _i36;
import 'data/core/repository/production_geo_location_repository.dart' as _i88;
import 'data/experience_log/repository/development_experience_log_repository.dart' as _i71;
import 'data/experience_log/repository/production_experience_log_repository.dart' as _i223;
import 'data/experience_management/repository/development_experience_management_repository.dart' as _i76;
import 'data/experience_management/repository/production_experience_management_repository.dart' as _i224;
import 'data/experience_navigation/repository/development_experience_navigation_repository.dart' as _i79;
import 'data/experience_navigation/repository/production_experience_navigation_repository.dart' as _i225;
import 'data/main_feed/repository/development_main_feed_repository.dart' as _i116;
import 'data/main_feed/repository/production_main_feed_repository.dart' as _i114;
import 'data/notifications/repository/development_notification_repository.dart' as _i126;
import 'data/notifications/repository/production_notification_repository.dart' as _i125;
import 'data/options/repository/development_local_options_repository.dart' as _i108;
import 'data/options/repository/development_remote_options_repository.dart' as _i151;
import 'data/options/repository/production_local_options_repository.dart' as _i107;
import 'data/options/repository/production_remote_options_repository.dart' as _i149;
import 'data/profile/repository/development_profile_repository.dart' as _i138;
import 'data/profile/repository/production_profile_repository.dart' as _i139;
import 'data/search/repository/development_search_repository.dart' as _i162;
import 'data/search/repository/production_search_repository.dart' as _i163;
import 'data/store/repository/development_store_repository.dart' as _i170;
import 'data/store/repository/production_store_repository.dart' as _i172;
import 'data/tag_management/repository/development_tag_management_repository.dart' as _i182;
import 'data/tag_management/repository/development_tag_repository.dart' as _i177;
import 'data/tag_management/repository/production_tag_management_repository.dart' as _i181;
import 'data/tag_management/repository/production_tag_repository.dart' as _i175;
import 'domain/achievement_management/repository/achievement_repository_interface.dart' as _i6;
import 'domain/achievement_management/repository/achievement_repository_mock.dart' as _i7;
import 'domain/achievement_management/use_case/award_achievement.dart' as _i18;
import 'domain/achievement_management/use_case/create_achievement.dart' as _i39;
import 'domain/achievement_management/use_case/delete_achievement.dart' as _i43;
import 'domain/achievement_management/use_case/edit_achievement.dart' as _i58;
import 'domain/achievement_management/use_case/get_achievement.dart' as _i91;
import 'domain/achievement_management/use_case/use_case_mocks.dart' as _i19;
import 'domain/achievement_management/use_case/watch_all_achievements.dart' as _i190;
import 'domain/authentication/repository/authentication_repository_interface.dart' as _i15;
import 'domain/authentication/repository/authentication_repository_mock.dart' as _i17;
import 'domain/authentication/use_case/get_logged_in_user.dart' as _i95;
import 'domain/authentication/use_case/log_in.dart' as _i109;
import 'domain/authentication/use_case/log_in_google.dart' as _i111;
import 'domain/authentication/use_case/log_out.dart' as _i112;
import 'domain/authentication/use_case/register.dart' as _i146;
import 'domain/authentication/use_case/use_case_mocks.dart' as _i96;
import 'domain/comments/repository/comment_repository_interface.dart' as _i31;
import 'domain/comments/repository/comment_repository_mock.dart' as _i32;
import 'domain/comments/use_case/delete_comment.dart' as _i46;
import 'domain/comments/use_case/edit_comment.dart' as _i59;
import 'domain/comments/use_case/post_comment.dart' as _i132;
import 'domain/comments/use_case/use_case_mocks.dart' as _i47;
import 'domain/comments/use_case/watch_experience_comments.dart' as _i193;
import 'domain/comments/use_case/watch_user_comments.dart' as _i216;
import 'domain/core/repository/core_repository_interface.dart' as _i35;
import 'domain/core/repository/core_repository_mock.dart' as _i38;
import 'domain/core/repository/geo_location_repository_interface.dart' as _i87;
import 'domain/core/repository/geo_location_repository_mock.dart' as _i90;
import 'domain/core/use_case/delete_cache.dart' as _i44;
import 'domain/core/use_case/get_current_location.dart' as _i93;
import 'domain/core/use_case/is_logged_in_user.dart' as _i100;
import 'domain/core/use_case/use_case.dart' as _i121;
import 'domain/core/use_case/use_case_mocks.dart' as _i45;
import 'domain/experience_log/repository/experience_log_repository_interface.dart' as _i69;
import 'domain/experience_log/repository/experience_log_repository_mock.dart' as _i70;
import 'domain/experience_log/use_case/add_experience_to_log.dart' as _i10;
import 'domain/experience_log/use_case/dismiss_experience_from_log.dart' as _i56;
import 'domain/experience_log/use_case/use_case_mocks.dart' as _i11;
import 'domain/experience_log/use_case/watch_user_log.dart' as _i218;
import 'domain/experience_management/repository/experience_management_repository_interface.dart' as _i75;
import 'domain/experience_management/repository/experience_management_repository_mock.dart' as _i77;
import 'domain/experience_management/use_case/create_experience.dart' as _i40;
import 'domain/experience_management/use_case/edit_experience.dart' as _i60;
import 'domain/experience_management/use_case/get_experience.dart' as _i94;
import 'domain/experience_management/use_case/use_case_mocks.dart' as _i41;
import 'domain/experience_navigation/repository/experience_navigation_repository_interface.dart' as _i78;
import 'domain/experience_navigation/repository/experience_navigation_repository_mock.dart' as _i80;
import 'domain/experience_navigation/use_case/dislike_experience.dart' as _i54;
import 'domain/experience_navigation/use_case/finish_experience.dart' as _i82;
import 'domain/experience_navigation/use_case/like_experience.dart' as _i101;
import 'domain/experience_navigation/use_case/load_surrounding_experiences.dart' as _i102;
import 'domain/experience_navigation/use_case/rate_difficulty.dart' as _i143;
import 'domain/experience_navigation/use_case/reward_user.dart' as _i154;
import 'domain/experience_navigation/use_case/use_case_mocks.dart' as _i55;
import 'domain/experience_navigation/use_case/watch_recommended_experiences.dart' as _i206;
import 'domain/main_feed/repository/main_feed_repository_interface.dart' as _i113;
import 'domain/main_feed/repository/main_feed_repository_mock.dart' as _i115;
import 'domain/main_feed/use_case/use_case_mocks.dart' as _i198;
import 'domain/main_feed/use_case/watch_feed.dart' as _i197;
import 'domain/notifications/repository/notification_repository_interface.dart' as _i123;
import 'domain/notifications/repository/notification_repository_mock.dart' as _i124;
import 'domain/notifications/use_case/check_notification.dart' as _i26;
import 'domain/notifications/use_case/delete_notification.dart' as _i49;
import 'domain/notifications/use_case/delete_user_notifications.dart' as _i53;
import 'domain/notifications/use_case/send_notification.dart' as _i167;
import 'domain/notifications/use_case/use_case_mocks.dart' as _i27;
import 'domain/notifications/use_case/watch_if_new_notifications.dart' as _i201;
import 'domain/notifications/use_case/watch_notifications.dart' as _i202;
import 'domain/options/repository/local_options_repository_interface.dart' as _i105;
import 'domain/options/repository/local_options_repository_mock.dart' as _i106;
import 'domain/options/repository/remote_options_repository_interface.dart' as _i148;
import 'domain/options/repository/remote_options_repository_mock.dart' as _i150;
import 'domain/options/use_case/delete_user.dart' as _i51;
import 'domain/options/use_case/save_global_options.dart' as _i156;
import 'domain/options/use_case/use_case_mocks.dart' as _i52;
import 'domain/profile/repository/profile_repository_interface.dart' as _i137;
import 'domain/profile/repository/profile_repository_mock.dart' as _i140;
import 'domain/profile/use_case/block_user.dart' as _i21;
import 'domain/profile/use_case/delete_experience.dart' as _i48;
import 'domain/profile/use_case/edit_user.dart' as _i62;
import 'domain/profile/use_case/follow_user.dart' as _i86;
import 'domain/profile/use_case/get_amout_of_followers.dart' as _i92;
import 'domain/profile/use_case/load_user.dart' as _i103;
import 'domain/profile/use_case/remove_experience_liked.dart' as _i152;
import 'domain/profile/use_case/un_block_user.dart' as _i186;
import 'domain/profile/use_case/un_follow_user.dart' as _i187;
import 'domain/profile/use_case/use_case_mocks.dart' as _i22;
import 'domain/profile/use_case/watch_blocked_users.dart' as _i192;
import 'domain/profile/use_case/watch_experiences_created.dart' as _i194;
import 'domain/profile/use_case/watch_experiences_done.dart' as _i195;
import 'domain/profile/use_case/watch_experiences_liked.dart' as _i196;
import 'domain/profile/use_case/watch_followed_users.dart' as _i199;
import 'domain/profile/use_case/watch_following_users.dart' as _i200;
import 'domain/profile/use_case/watch_user_achievements.dart' as _i215;
import 'domain/profile/use_case/watch_user_interests.dart' as _i217;
import 'domain/search/repository/search_repository_interface.dart' as _i161;
import 'domain/search/repository/search_repository_mock.dart' as _i164;
import 'domain/search/use_case/use_case_mocks.dart' as _i208;
import 'domain/search/use_case/watch_search_experiences_by_difficulty.dart' as _i207;
import 'domain/search/use_case/watch_search_experiences_by_name.dart' as _i209;
import 'domain/search/use_case/watch_search_experiences_by_tags.dart' as _i210;
import 'domain/search/use_case/watch_search_tags_by_name.dart' as _i211;
import 'domain/search/use_case/watch_search_users_by_name.dart' as _i212;
import 'domain/search/use_case/watch_search_users_by_username.dart' as _i213;
import 'domain/store/repository/store_repository_interface.dart' as _i169;
import 'domain/store/repository/store_repository_mock.dart' as _i171;
import 'domain/store/use_case/buy_coin.dart' as _i220;
import 'domain/store/use_case/buy_item.dart' as _i221;
import 'domain/store/use_case/watch_owned_items.dart' as _i203;
import 'domain/store/use_case/watch_purchasable_items.dart' as _i204;
import 'domain/tag_management/repository/tag_management_repository_interface.dart' as _i180;
import 'domain/tag_management/repository/tag_management_repository_mock.dart' as _i183;
import 'domain/tag_management/repository/tag_repository_interface.dart' as _i174;
import 'domain/tag_management/repository/tag_repository_mock.dart' as _i176;
import 'domain/tag_management/use_case/add_tag_to_interests.dart' as _i12;
import 'domain/tag_management/use_case/create_tag.dart' as _i42;
import 'domain/tag_management/use_case/delete_tag.dart' as _i50;
import 'domain/tag_management/use_case/dismiss_tag_from_interests.dart' as _i57;
import 'domain/tag_management/use_case/edit_tag.dart' as _i61;
import 'domain/tag_management/use_case/get_tag.dart' as _i97;
import 'domain/tag_management/use_case/get_tag_creator.dart' as _i98;
import 'domain/tag_management/use_case/use_case_mocks.dart' as _i13;
import 'domain/tag_management/use_case/watch_all_tags.dart' as _i191;
import 'domain/tag_management/use_case/watch_tags_by_creator.dart' as _i214;

const String _test = 'test';
const String _dev = 'dev';
const String _prod = 'prod';
// ignore_for_file: unnecessary_lambdas
// ignore_for_file: lines_longer_than_80_chars
/// initializes the registration of provided dependencies inside of [GetIt]
_i1.GetIt $initGetIt(_i1.GetIt get, {String? environment, _i2.EnvironmentFilter? environmentFilter}) {
  final gh = _i2.GetItHelper(get, environment, environmentFilter);
  final firebaseInjectableModule = _$FirebaseInjectableModule();
  gh.factory<_i3.AchievementManagementActorBloc>(() => _i3.AchievementManagementActorBloc());
  gh.factory<_i4.AchievementManagementFormBloc>(() => _i4.AchievementManagementFormBloc());
  gh.factory<_i5.AchievementManagementWatcherBloc>(() => _i5.AchievementManagementWatcherBloc());
  gh.lazySingleton<_i6.AchievementRepositoryInterface>(() => _i7.MockAchievementRepository(), registerFor: {_test});
  gh.lazySingleton<_i6.AchievementRepositoryInterface>(() => _i8.DevelopmentAchievementRepository(), registerFor: {_dev});
  gh.lazySingleton<_i6.AchievementRepositoryInterface>(() => _i9.ProductionAchievementRepository(), registerFor: {_prod});
  gh.lazySingleton<_i10.AddExperienceToLog>(() => _i11.MockAddExperienceToLog(), registerFor: {_test});
  gh.lazySingleton<_i12.AddTagToInterests>(() => _i13.MockAddTagToInterests(), registerFor: {_test});
  gh.factory<_i14.AuthenticationBloc>(() => _i14.AuthenticationBloc());
  gh.lazySingleton<_i15.AuthenticationRepositoryInterface>(() => _i16.DevelopmentAuthenticationRepository(), registerFor: {_dev});
  gh.lazySingleton<_i15.AuthenticationRepositoryInterface>(() => _i17.MockAuthenticationRepository(), registerFor: {_test});
  gh.lazySingleton<_i18.AwardAchievement>(() => _i19.MockAwardAchievement(), registerFor: {_test});
  gh.lazySingleton<_i18.AwardAchievement>(() => _i18.AwardAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.factory<_i20.BlockActorBloc>(() => _i20.BlockActorBloc());
  gh.lazySingleton<_i21.BlockUser>(() => _i22.MockBlockUser(), registerFor: {_test});
  gh.factory<_i23.BlockedWatcherBloc>(() => _i23.BlockedWatcherBloc());
  gh.factory<_i24.BuyCoinsBloc>(() => _i24.BuyCoinsBloc());
  gh.factory<_i25.BuyItemBloc>(() => _i25.BuyItemBloc());
  gh.lazySingleton<_i26.CheckNotification>(() => _i27.MockCheckNotification(), registerFor: {_test});
  gh.factory<_i28.CloudStorageService>(() => _i28.CloudStorageService());
  gh.factory<_i29.CommentActorBloc>(() => _i29.CommentActorBloc());
  gh.factory<_i30.CommentFormBloc>(() => _i30.CommentFormBloc());
  gh.lazySingleton<_i31.CommentRepositoryInterface>(() => _i32.MockCommentRepository(), registerFor: {_test});
  gh.lazySingleton<_i31.CommentRepositoryInterface>(() => _i33.DevelopmentCommentRepository(), registerFor: {_dev});
  gh.factory<_i34.CommentWatcherBloc>(() => _i34.CommentWatcherBloc());
  gh.lazySingleton<_i35.CoreRepositoryInterface>(() => _i36.ProductionCoreRepository(), registerFor: {_prod});
  gh.lazySingleton<_i35.CoreRepositoryInterface>(() => _i37.DevelopmentCoreRepository(), registerFor: {_dev});
  gh.lazySingleton<_i35.CoreRepositoryInterface>(() => _i38.MockCoreRepository(), registerFor: {_test});
  gh.lazySingleton<_i39.CreateAchievement>(() => _i39.CreateAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i39.CreateAchievement>(() => _i19.MockCreateAchievement(), registerFor: {_test});
  gh.lazySingleton<_i40.CreateExperience>(() => _i41.MockCreateExperience(), registerFor: {_test});
  gh.lazySingleton<_i42.CreateTag>(() => _i13.MockCreateTag(), registerFor: {_test});
  gh.lazySingleton<_i43.DeleteAchievement>(() => _i43.DeleteAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i43.DeleteAchievement>(() => _i19.MockDeleteAchievement(), registerFor: {_test});
  gh.lazySingleton<_i44.DeleteCache>(() => _i44.DeleteCache(get<_i35.CoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i44.DeleteCache>(() => _i45.MockDeleteCache(), registerFor: {_test});
  gh.lazySingleton<_i46.DeleteComment>(() => _i47.MockDeleteComment(), registerFor: {_test});
  gh.lazySingleton<_i46.DeleteComment>(() => _i46.DeleteComment(get<_i31.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i48.DeleteExperience>(() => _i22.MockDeleteExperience(), registerFor: {_test});
  gh.lazySingleton<_i49.DeleteNotification>(() => _i27.MockDeleteNotification(), registerFor: {_test});
  gh.lazySingleton<_i50.DeleteTag>(() => _i13.MockDeleteTag(), registerFor: {_test});
  gh.lazySingleton<_i51.DeleteUser>(() => _i52.MockDeleteUser(), registerFor: {_test});
  gh.lazySingleton<_i53.DeleteUserNotifications>(() => _i27.MockDeleteUserNotifications(), registerFor: {_test});
  gh.lazySingleton<_i54.DislikeExperience>(() => _i55.MockDislikeExperience(), registerFor: {_test});
  gh.lazySingleton<_i56.DismissExperienceFromLog>(() => _i11.MockDismissExperienceFromLog(), registerFor: {_test});
  gh.lazySingleton<_i57.DismissTagFromInterests>(() => _i13.MockDismissTagFromInterests(), registerFor: {_test});
  gh.lazySingleton<_i58.EditAchievement>(() => _i19.MockEditAchievement(), registerFor: {_test});
  gh.lazySingleton<_i58.EditAchievement>(() => _i58.EditAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i59.EditComment>(() => _i59.EditComment(get<_i31.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i59.EditComment>(() => _i47.MockEditComment(), registerFor: {_test});
  gh.lazySingleton<_i60.EditExperience>(() => _i41.MockEditExperience(), registerFor: {_test});
  gh.lazySingleton<_i61.EditTag>(() => _i13.MockEditTag(), registerFor: {_test});
  gh.lazySingleton<_i62.EditUser>(() => _i22.MockEditUser(), registerFor: {_test});
  gh.factory<_i63.ExperienceCardActorBloc>(() => _i63.ExperienceCardActorBloc());
  gh.factory<_i64.ExperienceCardLikeCheckBloc>(() => _i64.ExperienceCardLikeCheckBloc());
  gh.factory<_i65.ExperienceEditingFormBloc>(() => _i65.ExperienceEditingFormBloc());
  gh.factory<_i66.ExperienceFinishActorBloc>(() => _i66.ExperienceFinishActorBloc());
  gh.factory<_i67.ExperienceLikeActorBloc>(() => _i67.ExperienceLikeActorBloc());
  gh.factory<_i68.ExperienceLogActorBloc>(() => _i68.ExperienceLogActorBloc());
  gh.lazySingleton<_i69.ExperienceLogRepositoryInterface>(() => _i70.MockExperienceLogRepository(), registerFor: {_test});
  gh.lazySingleton<_i69.ExperienceLogRepositoryInterface>(() => _i71.DevelopmentExperienceLogRepository(), registerFor: {_dev});
  gh.factory<_i72.ExperienceLogWatcherBloc>(() => _i72.ExperienceLogWatcherBloc());
  gh.factory<_i73.ExperienceManagementActorBloc>(() => _i73.ExperienceManagementActorBloc());
  gh.factory<_i74.ExperienceManagementFormBloc>(() => _i74.ExperienceManagementFormBloc());
  gh.lazySingleton<_i75.ExperienceManagementRepositoryInterface>(() => _i76.DevelopmentExperienceManagementRepository(), registerFor: {_dev});
  gh.lazySingleton<_i75.ExperienceManagementRepositoryInterface>(() => _i77.MockExperienceManagementRepository(), registerFor: {_test});
  gh.lazySingleton<_i78.ExperienceNavigationRepositoryInterface>(() => _i79.DevelopmentExperienceNavigationRepository(), registerFor: {_dev});
  gh.lazySingleton<_i78.ExperienceNavigationRepositoryInterface>(() => _i80.MockExperienceNavigationRepository(), registerFor: {_test});
  gh.factory<_i81.ExperienceNavigationWatcherBloc>(() => _i81.ExperienceNavigationWatcherBloc());
  gh.lazySingleton<_i82.FinishExperience>(() => _i55.MockFinishExperience(), registerFor: {_test});
  gh.lazySingleton<_i82.FinishExperience>(() => _i82.FinishExperience(get<_i78.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i83.FirebaseAuth>(() => firebaseInjectableModule.firebaseAuth);
  gh.lazySingleton<_i84.FirebaseFirestore>(() => firebaseInjectableModule.firestore);
  gh.factory<_i85.FollowActorBloc>(() => _i85.FollowActorBloc());
  gh.lazySingleton<_i86.FollowUser>(() => _i22.MockFollowUser(), registerFor: {_test});
  gh.lazySingleton<_i87.GeoLocationRepositoryInterface>(() => _i88.ProductionGeoLocationRepository(), registerFor: {_prod});
  gh.lazySingleton<_i87.GeoLocationRepositoryInterface>(() => _i89.DevelopmentGeoLocationRepository(), registerFor: {_dev});
  gh.lazySingleton<_i87.GeoLocationRepositoryInterface>(() => _i90.MockGeoLocationRepository(), registerFor: {_test});
  gh.lazySingleton<_i91.GetAchievement>(() => _i19.MockGetAchievement(), registerFor: {_test});
  gh.lazySingleton<_i91.GetAchievement>(() => _i91.GetAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i92.GetAmountOfFollowers>(() => _i22.MockGetAmountOfFollowers(), registerFor: {_test});
  gh.lazySingleton<_i93.GetCurrentLocation>(() => _i93.GetCurrentLocation(get<_i87.GeoLocationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i93.GetCurrentLocation>(() => _i45.MockGetCurrentLocation(), registerFor: {_test});
  gh.lazySingleton<_i94.GetExperience>(() => _i41.MockGetExperience(), registerFor: {_test});
  gh.lazySingleton<_i94.GetExperience>(() => _i94.GetExperience(get<_i75.ExperienceManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i95.GetLoggedInUser>(() => _i96.MockGetLoggedInUser(), registerFor: {_test});
  gh.lazySingleton<_i95.GetLoggedInUser>(() => _i95.GetLoggedInUser(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i97.GetTag>(() => _i13.MockGetTag(), registerFor: {_test});
  gh.lazySingleton<_i98.GetTagCreator>(() => _i13.MockGetTagCreator(), registerFor: {_test});
  gh.lazySingleton<_i99.GoogleSignIn>(() => firebaseInjectableModule.googleSignIn);
  gh.lazySingleton<_i100.IsLoggedInUser>(() => _i100.IsLoggedInUser(), registerFor: {_dev, _prod});
  gh.lazySingleton<_i100.IsLoggedInUser>(() => _i45.MockIsLoggedInUser(), registerFor: {_test});
  gh.lazySingleton<_i101.LikeExperience>(() => _i101.LikeExperience(get<_i78.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i101.LikeExperience>(() => _i55.MockLikeExperience(), registerFor: {_test});
  gh.lazySingleton<_i102.LoadSurroundingExperiences>(() => _i55.MockLoadSurroundingExperiences(), registerFor: {_test});
  gh.lazySingleton<_i102.LoadSurroundingExperiences>(() => _i102.LoadSurroundingExperiences(get<_i78.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i103.LoadUser>(() => _i22.MockLoadUser(), registerFor: {_test});
  gh.factory<_i104.LoadUserBloc>(() => _i104.LoadUserBloc());
  gh.lazySingleton<_i105.LocalOptionsRepositoryInterface>(() => _i106.MockLocalOptionsRepository(), registerFor: {_test});
  gh.lazySingleton<_i105.LocalOptionsRepositoryInterface>(() => _i107.ProductionLocalOptionsRepository(), registerFor: {_prod});
  gh.lazySingleton<_i105.LocalOptionsRepositoryInterface>(() => _i108.DevelopmentLocalOptionsRepository(), registerFor: {_dev});
  gh.lazySingleton<_i109.LogIn>(() => _i109.LogIn(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i109.LogIn>(() => _i96.MockLogIn(), registerFor: {_test});
  gh.factory<_i110.LogInFormBloc>(() => _i110.LogInFormBloc());
  gh.lazySingleton<_i111.LogInGoogle>(() => _i96.MockLogInGoogle(), registerFor: {_test});
  gh.lazySingleton<_i111.LogInGoogle>(() => _i111.LogInGoogle(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i112.LogOut>(() => _i112.LogOut(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i112.LogOut>(() => _i96.MockLogOut(), registerFor: {_test});
  gh.lazySingleton<_i113.MainFeedRepositoryInterface>(() => _i114.ProductionMainFeedRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i113.MainFeedRepositoryInterface>(() => _i115.MockMainFeedRepository(), registerFor: {_test});
  gh.lazySingleton<_i113.MainFeedRepositoryInterface>(() => _i116.DevelopmentMainFeedRepository(), registerFor: {_dev});
  gh.factory<_i117.MainFeedWatcherBloc>(() => _i117.MainFeedWatcherBloc());
  gh.factory<_i118.MapControllerBloc>(() => _i118.MapControllerBloc());
  gh.factory<_i119.NavigationActorBloc>(() => _i119.NavigationActorBloc());
  gh.factory<_i120.NewNotificationsWatcherBloc>(() => _i120.NewNotificationsWatcherBloc());
  gh.lazySingleton<_i121.NoParams>(() => _i121.NoParams());
  gh.factory<_i122.NotificationActorBloc>(() => _i122.NotificationActorBloc());
  gh.lazySingleton<_i123.NotificationRepositoryInterface>(() => _i124.MockNotificationRepository(), registerFor: {_test});
  gh.lazySingleton<_i123.NotificationRepositoryInterface>(() => _i125.ProductionNotificationRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i123.NotificationRepositoryInterface>(() => _i126.DevelopmentNotificationRepository(), registerFor: {_dev});
  gh.factory<_i127.NotificationsWatcherBloc>(() => _i127.NotificationsWatcherBloc());
  gh.factory<_i128.ObjectiveFormBloc>(() => _i128.ObjectiveFormBloc());
  gh.factory<_i129.ObjectivesCreationBloc>(() => _i129.ObjectivesCreationBloc());
  gh.factory<_i130.ObjectivesTrackerBloc>(() => _i130.ObjectivesTrackerBloc());
  gh.factory<_i131.OptionsFormBloc>(() => _i131.OptionsFormBloc());
  gh.lazySingleton<_i132.PostComment>(() => _i132.PostComment(get<_i31.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i132.PostComment>(() => _i47.MockPostComment(), registerFor: {_test});
  gh.factory<_i133.ProfileAchievementsWatcherBloc>(() => _i133.ProfileAchievementsWatcherBloc());
  gh.factory<_i134.ProfileEditingFormBloc>(() => _i134.ProfileEditingFormBloc());
  gh.factory<_i135.ProfileExperiencesWatcherBloc>(() => _i135.ProfileExperiencesWatcherBloc());
  gh.factory<_i136.ProfileInterestsWatcherBloc>(() => _i136.ProfileInterestsWatcherBloc());
  gh.lazySingleton<_i137.ProfileRepositoryInterface>(() => _i138.DevelopmentProfileRepository(), registerFor: {_dev});
  gh.lazySingleton<_i137.ProfileRepositoryInterface>(() => _i139.ProductionProfileRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i137.ProfileRepositoryInterface>(() => _i140.MockProfileRepository(), registerFor: {_test});
  gh.factory<_i141.ProfileUsersWatcherBloc>(() => _i141.ProfileUsersWatcherBloc());
  gh.factory<_i142.ProfileWatcherBloc>(() => _i142.ProfileWatcherBloc());
  gh.lazySingleton<_i143.RateDifficulty>(() => _i55.MockRateDifficulty(), registerFor: {_test});
  gh.lazySingleton<_i143.RateDifficulty>(() => _i143.RateDifficulty(get<_i78.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.factory<_i144.RateExperienceDifficultyActorBloc>(() => _i144.RateExperienceDifficultyActorBloc());
  gh.factory<_i145.RecommendedExperiencesWatcherBloc>(() => _i145.RecommendedExperiencesWatcherBloc());
  gh.lazySingleton<_i146.Register>(() => _i146.Register(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i146.Register>(() => _i96.MockRegister(), registerFor: {_test});
  gh.factory<_i147.RegistrationFormBloc>(() => _i147.RegistrationFormBloc());
  gh.lazySingleton<_i148.RemoteOptionsRepositoryInterface>(() => _i149.ProductionRemoteOptionsRepository(), registerFor: {_prod});
  gh.lazySingleton<_i148.RemoteOptionsRepositoryInterface>(() => _i150.MockRemoteOptionsRepository(), registerFor: {_test});
  gh.lazySingleton<_i148.RemoteOptionsRepositoryInterface>(() => _i151.DevelopmentRemoteOptionsRepository(), registerFor: {_dev});
  gh.lazySingleton<_i152.RemoveExperienceLiked>(() => _i22.MockRemoveExperienceLiked(), registerFor: {_test});
  gh.lazySingleton<_i152.RemoveExperienceLiked>(() => _i152.RemoveExperienceLiked(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.factory<_i153.RewardFormBloc>(() => _i153.RewardFormBloc());
  gh.lazySingleton<_i154.RewardUser>(() => _i154.RewardUser(get<_i78.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i154.RewardUser>(() => _i55.MockRewardUser(), registerFor: {_test});
  gh.factory<_i155.RewardsCreationBloc>(() => _i155.RewardsCreationBloc());
  gh.lazySingleton<_i156.SaveGlobalOptions>(() => _i156.SaveGlobalOptions(get<_i148.RemoteOptionsRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i156.SaveGlobalOptions>(() => _i52.MockSaveGlobalOptions(), registerFor: {_test});
  gh.factory<_i157.SearchByNameFormBloc>(() => _i157.SearchByNameFormBloc());
  gh.factory<_i158.SearchExperiencesByDifficultyBloc>(() => _i158.SearchExperiencesByDifficultyBloc());
  gh.factory<_i159.SearchExperiencesByNameWatcherBloc>(() => _i159.SearchExperiencesByNameWatcherBloc());
  gh.factory<_i160.SearchExperiencesByTagsBloc>(() => _i160.SearchExperiencesByTagsBloc());
  gh.lazySingleton<_i161.SearchRepositoryInterface>(() => _i162.DevelopmentSearchRepository(), registerFor: {_dev});
  gh.lazySingleton<_i161.SearchRepositoryInterface>(() => _i163.ProductionSearchRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i161.SearchRepositoryInterface>(() => _i164.MockSearchRepository(), registerFor: {_test});
  gh.factory<_i165.SearchTagsByNameWatcherBloc>(() => _i165.SearchTagsByNameWatcherBloc());
  gh.factory<_i166.SearchUsersByNameWatcherBloc>(() => _i166.SearchUsersByNameWatcherBloc());
  gh.lazySingleton<_i167.SendNotification>(() => _i167.SendNotification(get<_i123.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i167.SendNotification>(() => _i27.MockSendNotification(), registerFor: {_test});
  gh.factory<_i168.StoreNavigationActorBloc>(() => _i168.StoreNavigationActorBloc());
  gh.lazySingleton<_i169.StoreRepositoryInterface>(() => _i170.DevelopmentStoreRepository(), registerFor: {_dev});
  gh.lazySingleton<_i169.StoreRepositoryInterface>(() => _i171.MockStoreRepository(), registerFor: {_test});
  gh.lazySingleton<_i169.StoreRepositoryInterface>(() => _i172.ProductionStoreRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.factory<_i173.TagCardActorBloc>(() => _i173.TagCardActorBloc());
  gh.lazySingleton<_i174.TagCoreRepositoryInterface>(() => _i175.ProductionTagRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i174.TagCoreRepositoryInterface>(() => _i176.MockTagRepository(), registerFor: {_test});
  gh.lazySingleton<_i174.TagCoreRepositoryInterface>(() => _i177.DevelopmentTagRepository(), registerFor: {_dev});
  gh.factory<_i178.TagManagementActorBloc>(() => _i178.TagManagementActorBloc());
  gh.factory<_i179.TagManagementFormBloc>(() => _i179.TagManagementFormBloc());
  gh.lazySingleton<_i180.TagManagementRepositoryInterface>(() => _i181.ProductionTagManagementRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i180.TagManagementRepositoryInterface>(() => _i182.DevelopmentTagManagementRepository(), registerFor: {_dev});
  gh.lazySingleton<_i180.TagManagementRepositoryInterface>(() => _i183.MockTagManagementRepository(), registerFor: {_test});
  gh.factory<_i184.TagManagementWatcherBloc>(() => _i184.TagManagementWatcherBloc());
  gh.factory<_i185.TagSelectorBloc>(() => _i185.TagSelectorBloc());
  gh.lazySingleton<_i186.UnBlockUser>(() => _i186.UnBlockUser(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i186.UnBlockUser>(() => _i22.MockUnBlockUser(), registerFor: {_test});
  gh.lazySingleton<_i187.UnFollowUser>(() => _i187.UnFollowUser(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i187.UnFollowUser>(() => _i22.MockUnFollowUser(), registerFor: {_test});
  gh.factory<_i188.UserActorBloc>(() => _i188.UserActorBloc());
  gh.factory<_i189.UserProfileButtonWatcherBloc>(() => _i189.UserProfileButtonWatcherBloc());
  gh.lazySingleton<_i190.WatchAllAchievements>(() => _i190.WatchAllAchievements(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i190.WatchAllAchievements>(() => _i19.MockGetAllAchievements(), registerFor: {_test});
  gh.lazySingleton<_i191.WatchAllTags>(() => _i13.MockGetAllTags(), registerFor: {_test});
  gh.lazySingleton<_i191.WatchAllTags>(() => _i191.WatchAllTags(get<_i174.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i192.WatchBlockedUsers>(() => _i192.WatchBlockedUsers(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i192.WatchBlockedUsers>(() => _i22.MockLoadBlockedUsers(), registerFor: {_test});
  gh.lazySingleton<_i193.WatchExperienceComments>(() => _i47.MockGetExperienceComments(), registerFor: {_test});
  gh.lazySingleton<_i193.WatchExperienceComments>(() => _i193.WatchExperienceComments(get<_i31.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i194.WatchExperiencesCreated>(() => _i22.MockLoadExperiencesCreated(), registerFor: {_test});
  gh.lazySingleton<_i194.WatchExperiencesCreated>(() => _i194.WatchExperiencesCreated(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i195.WatchExperiencesDone>(() => _i195.WatchExperiencesDone(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i195.WatchExperiencesDone>(() => _i22.MockLoadExperiencesDone(), registerFor: {_test});
  gh.lazySingleton<_i196.WatchExperiencesLiked>(() => _i196.WatchExperiencesLiked(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i196.WatchExperiencesLiked>(() => _i22.MockLoadExperiencesLiked(), registerFor: {_test});
  gh.lazySingleton<_i197.WatchFeed>(() => _i198.MockFillFeed(), registerFor: {_test});
  gh.lazySingleton<_i197.WatchFeed>(() => _i197.WatchFeed(get<_i113.MainFeedRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i199.WatchFollowedUsers>(() => _i22.MockLoadFollowedUsers(), registerFor: {_test});
  gh.lazySingleton<_i199.WatchFollowedUsers>(() => _i199.WatchFollowedUsers(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i200.WatchFollowingUsers>(() => _i200.WatchFollowingUsers(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i200.WatchFollowingUsers>(() => _i22.MockLoadFollowingUsers(), registerFor: {_test});
  gh.lazySingleton<_i201.WatchIfNewNotifications>(() => _i201.WatchIfNewNotifications(get<_i123.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i202.WatchNotifications>(() => _i202.WatchNotifications(get<_i123.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i202.WatchNotifications>(() => _i27.MockLoadNotifications(), registerFor: {_test});
  gh.lazySingleton<_i203.WatchOwnedItems>(() => _i203.WatchOwnedItems(get<_i169.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i204.WatchPurchasableItems>(() => _i204.WatchPurchasableItems(get<_i169.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.factory<_i205.WatchPurchasableItemsBloc>(() => _i205.WatchPurchasableItemsBloc());
  gh.lazySingleton<_i206.WatchRecommendedExperiences>(() => _i206.WatchRecommendedExperiences(get<_i78.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i207.WatchSearchExperiencesByDifficulty>(() => _i207.WatchSearchExperiencesByDifficulty(get<_i161.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i207.WatchSearchExperiencesByDifficulty>(() => _i208.MockSearchExperiencesByDifficulty(), registerFor: {_test});
  gh.lazySingleton<_i209.WatchSearchExperiencesByName>(() => _i209.WatchSearchExperiencesByName(get<_i161.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i209.WatchSearchExperiencesByName>(() => _i208.MockSearchExperiencesByName(), registerFor: {_test});
  gh.lazySingleton<_i210.WatchSearchExperiencesByTags>(() => _i208.MockSearchExperiencesByTags(), registerFor: {_test});
  gh.lazySingleton<_i210.WatchSearchExperiencesByTags>(() => _i210.WatchSearchExperiencesByTags(get<_i161.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i211.WatchSearchTagsByName>(() => _i208.MockSearchTagsByName(), registerFor: {_test});
  gh.lazySingleton<_i211.WatchSearchTagsByName>(() => _i211.WatchSearchTagsByName(get<_i161.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i212.WatchSearchUsersByName>(() => _i208.MockSearchUsersByName(), registerFor: {_test});
  gh.lazySingleton<_i212.WatchSearchUsersByName>(() => _i212.WatchSearchUsersByName(get<_i161.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i213.WatchSearchUsersByUsername>(() => _i213.WatchSearchUsersByUsername(get<_i161.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i213.WatchSearchUsersByUsername>(() => _i208.MockSearchUsersByUsername(), registerFor: {_test});
  gh.lazySingleton<_i214.WatchTagsByCreator>(() => _i214.WatchTagsByCreator(get<_i174.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i214.WatchTagsByCreator>(() => _i13.MockGetTagsByCreator(), registerFor: {_test});
  gh.lazySingleton<_i215.WatchUserAchievements>(() => _i215.WatchUserAchievements(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i215.WatchUserAchievements>(() => _i22.MockLoadUserAchievements(), registerFor: {_test});
  gh.lazySingleton<_i216.WatchUserComments>(() => _i216.WatchUserComments(get<_i31.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i216.WatchUserComments>(() => _i47.MockGetUserComments(), registerFor: {_test});
  gh.lazySingleton<_i217.WatchUserInterests>(() => _i22.MockLoadUserInterests(), registerFor: {_test});
  gh.lazySingleton<_i217.WatchUserInterests>(() => _i217.WatchUserInterests(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i218.WatchUserLog>(() => _i218.WatchUserLog(get<_i69.ExperienceLogRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i218.WatchUserLog>(() => _i11.MockLoadUserLog(), registerFor: {_test});
  gh.lazySingleton<_i10.AddExperienceToLog>(() => _i10.AddExperienceToLog(get<_i69.ExperienceLogRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i12.AddTagToInterests>(() => _i12.AddTagToInterests(get<_i174.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i15.AuthenticationRepositoryInterface>(() => _i219.ProductionAuthenticationRepository(get<_i83.FirebaseAuth>(), get<_i99.GoogleSignIn>(), get<_i84.FirebaseFirestore>()),
      registerFor: {_prod});
  gh.lazySingleton<_i21.BlockUser>(() => _i21.BlockUser(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i220.BuyCoins>(() => _i220.BuyCoins(get<_i169.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i221.BuyItem>(() => _i221.BuyItem(get<_i169.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i26.CheckNotification>(() => _i26.CheckNotification(get<_i123.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i31.CommentRepositoryInterface>(() => _i222.ProductionCommentRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i40.CreateExperience>(() => _i40.CreateExperience(get<_i75.ExperienceManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i42.CreateTag>(() => _i42.CreateTag(get<_i180.TagManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i48.DeleteExperience>(() => _i48.DeleteExperience(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i49.DeleteNotification>(() => _i49.DeleteNotification(get<_i123.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i50.DeleteTag>(() => _i50.DeleteTag(get<_i180.TagManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i51.DeleteUser>(() => _i51.DeleteUser(get<_i148.RemoteOptionsRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i53.DeleteUserNotifications>(() => _i53.DeleteUserNotifications(get<_i123.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i54.DislikeExperience>(() => _i54.DislikeExperience(get<_i78.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i56.DismissExperienceFromLog>(() => _i56.DismissExperienceFromLog(get<_i69.ExperienceLogRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i57.DismissTagFromInterests>(() => _i57.DismissTagFromInterests(get<_i174.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i60.EditExperience>(() => _i60.EditExperience(get<_i75.ExperienceManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i61.EditTag>(() => _i61.EditTag(get<_i180.TagManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i62.EditUser>(() => _i62.EditUser(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i69.ExperienceLogRepositoryInterface>(() => _i223.ProductionExperienceLogRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i75.ExperienceManagementRepositoryInterface>(() => _i224.ProductionExperienceManagementRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i78.ExperienceNavigationRepositoryInterface>(() => _i225.ProductionExperienceNavigationRepository(get<_i84.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i86.FollowUser>(() => _i86.FollowUser(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i92.GetAmountOfFollowers>(() => _i92.GetAmountOfFollowers(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i97.GetTag>(() => _i97.GetTag(get<_i180.TagManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i98.GetTagCreator>(() => _i98.GetTagCreator(get<_i174.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i103.LoadUser>(() => _i103.LoadUser(get<_i137.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  return get;
}

class _$FirebaseInjectableModule extends _i226.FirebaseInjectableModule {}
