// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

import 'package:cloud_firestore/cloud_firestore.dart' as _i85;
import 'package:firebase_auth/firebase_auth.dart' as _i84;
import 'package:get_it/get_it.dart' as _i1;
import 'package:google_sign_in/google_sign_in.dart' as _i101;
import 'package:injectable/injectable.dart' as _i2;

import 'application/achievement_management/achievement_management_actor/achievement_management_actor_bloc.dart' as _i3;
import 'application/achievement_management/achievement_management_form/achievement_management_form_bloc.dart' as _i4;
import 'application/achievement_management/achievement_management_watcher/achievement_management_watcher_bloc.dart' as _i5;
import 'application/authentication/authentication/authentication_bloc.dart' as _i14;
import 'application/authentication/log_in_form/log_in_form_bloc.dart' as _i112;
import 'application/authentication/registration_form/registration_form_bloc.dart' as _i150;
import 'application/comments/comment_actor/comment_actor_bloc.dart' as _i30;
import 'application/comments/comment_form/comment_form_bloc.dart' as _i31;
import 'application/comments/comment_watcher/comment_watcher_bloc.dart' as _i35;
import 'application/core/experience_card_actor/experience_card_actor_bloc.dart' as _i64;
import 'application/core/experience_card_like_check/experience_card_like_check_bloc.dart' as _i65;
import 'application/core/user_profile_button_watcher_bloc.dart' as _i192;
import 'application/experience_log/experience_log_actor/experience_log_actor_bloc.dart' as _i69;
import 'application/experience_log/experience_log_watcher/experience_log_watcher_bloc.dart' as _i73;
import 'application/experience_management/experience_editing_form/experience_editing_form_bloc.dart' as _i66;
import 'application/experience_management/experience_management_actor/experience_management_actor_bloc.dart' as _i74;
import 'application/experience_management/experience_management_form/experience_management_form_bloc.dart' as _i75;
import 'application/experience_management/objective_form/objective_form_bloc.dart' as _i130;
import 'application/experience_management/objectives_creation/objectives_creation_bloc.dart' as _i131;
import 'application/experience_management/reward_form/reward_form_bloc.dart' as _i156;
import 'application/experience_management/rewards_creation/rewards_creation_bloc.dart' as _i158;
import 'application/experience_navigation/experience_finish_actor/experience_finish_actor_bloc.dart' as _i67;
import 'application/experience_navigation/experience_like_actor/experience_like_actor_bloc.dart' as _i68;
import 'application/experience_navigation/experience_navigation_watcher/experience_navigation_watcher_bloc.dart' as _i82;
import 'application/experience_navigation/map_controller/map_controller_bloc.dart' as _i120;
import 'application/experience_navigation/objectives_tracker/objectives_tracker_bloc.dart' as _i132;
import 'application/experience_navigation/rate_experience_difficulty_actor/rate_experience_difficulty_actor_bloc.dart' as _i147;
import 'application/experience_navigation/recommended_experiences_watcher/recommended_experiences_watcher_bloc.dart' as _i148;
import 'application/main_feed/main_feed_watcher/main_feed_watcher_bloc.dart' as _i119;
import 'application/navigation/navigation_actor/navigation_actor_bloc.dart' as _i121;
import 'application/notifications/new_notifications_watcher/new_notifications_watcher_bloc.dart' as _i122;
import 'application/notifications/notification_actor/notification_actor_bloc.dart' as _i124;
import 'application/notifications/notifications_watcher/notifications_watcher_bloc.dart' as _i129;
import 'application/options/options_form/options_form_bloc.dart' as _i133;
import 'application/options/user_actor/user_actor_bloc.dart' as _i191;
import 'application/profile/block_actor/block_actor_bloc.dart' as _i20;
import 'application/profile/blocked_watcher/blocked_watcher_bloc.dart' as _i23;
import 'application/profile/follow_actor/follow_actor_bloc.dart' as _i86;
import 'application/profile/profile_achievements_watcher/profile_achievements_watcher_bloc.dart' as _i135;
import 'application/profile/profile_editing_form/profile_editing_form_bloc.dart' as _i136;
import 'application/profile/profile_experiences_watcher/profile_experiences_watcher_bloc.dart' as _i137;
import 'application/profile/profile_interests_watcher/profile_interests_watcher_bloc.dart' as _i138;
import 'application/profile/profile_users_watcher/profile_users_watcher_bloc.dart' as _i143;
import 'application/profile/profile_watcher/profile_watcher_bloc.dart' as _i144;
import 'application/search/search_by_name_form/search_by_name_form_bloc.dart' as _i160;
import 'application/search/search_experiences_by_difficulty/search_experiences_by_difficulty_bloc.dart' as _i161;
import 'application/search/search_experiences_by_name_watcher/search_experiences_by_name_watcher_bloc.dart' as _i162;
import 'application/search/search_experiences_by_tags/search_experiences_by_tags_bloc.dart' as _i163;
import 'application/search/search_tags_by_name_watcher/search_tags_by_name_watcher_bloc.dart' as _i168;
import 'application/search/search_users_by_name_watcher/search_users_by_name_watcher_bloc.dart' as _i169;
import 'application/search/tag_selector/tag_selector_bloc.dart' as _i188;
import 'application/store/buy_coins/buy_coins_bloc.dart' as _i24;
import 'application/store/buy_item/buy_item_bloc.dart' as _i25;
import 'application/store/buy_promotion_plan_actor/buy_promotion_plan_actor_bloc.dart' as _i26;
import 'application/store/load_user/load_user_bloc.dart' as _i106;
import 'application/store/promotion_plans_loader/promotion_plans_loader_bloc.dart' as _i145;
import 'application/store/purchasable_items_watcher/watch_purchasable_items_bloc.dart' as _i208;
import 'application/store/store_navigation_actor/store_navigation_actor_bloc.dart' as _i171;
import 'application/tag_management/tag_card_actor/tag_card_actor_bloc.dart' as _i176;
import 'application/tag_management/tag_management_actor/tag_management_actor_bloc.dart' as _i181;
import 'application/tag_management/tag_management_form/tag_management_form_bloc.dart' as _i182;
import 'application/tag_management/tag_management_watcher/tag_management_watcher_bloc.dart' as _i187;
import 'data/achievement_management/repository/development_achievement_repository.dart' as _i7;
import 'data/achievement_management/repository/production_achievement_repository.dart' as _i8;
import 'data/authentication/repository/development_authentication_repository.dart' as _i17;
import 'data/authentication/repository/production_authentication_repository.dart' as _i222;
import 'data/comments/repository/development_comment_repository.dart' as _i34;
import 'data/comments/repository/production_comment_repository.dart' as _i226;
import 'data/core/misc/cloud_storage/cloud_storage_service.dart' as _i29;
import 'data/core/modules/firebase_injectable_module.dart' as _i231;
import 'data/core/repository/development_core_repository.dart' as _i37;
import 'data/core/repository/development_geo_location_repository.dart' as _i90;
import 'data/core/repository/production_core_repository.dart' as _i38;
import 'data/core/repository/production_geo_location_repository.dart' as _i91;
import 'data/experience_log/repository/development_experience_log_repository.dart' as _i72;
import 'data/experience_log/repository/production_experience_log_repository.dart' as _i227;
import 'data/experience_management/repository/development_experience_management_repository.dart' as _i77;
import 'data/experience_management/repository/production_experience_management_repository.dart' as _i228;
import 'data/experience_navigation/repository/development_experience_navigation_repository.dart' as _i80;
import 'data/experience_navigation/repository/production_experience_navigation_repository.dart' as _i229;
import 'data/main_feed/repository/development_main_feed_repository.dart' as _i117;
import 'data/main_feed/repository/production_main_feed_repository.dart' as _i118;
import 'data/notifications/repository/development_notification_repository.dart' as _i127;
import 'data/notifications/repository/production_notification_repository.dart' as _i128;
import 'data/options/repository/development_local_options_repository.dart' as _i109;
import 'data/options/repository/development_remote_options_repository.dart' as _i153;
import 'data/options/repository/production_local_options_repository.dart' as _i110;
import 'data/options/repository/production_remote_options_repository.dart' as _i152;
import 'data/profile/repository/development_profile_repository.dart' as _i142;
import 'data/profile/repository/production_profile_repository.dart' as _i140;
import 'data/search/repository/development_search_repository.dart' as _i167;
import 'data/search/repository/production_search_repository.dart' as _i166;
import 'data/store/repository/development_store_repository.dart' as _i175;
import 'data/store/repository/production_store_repository.dart' as _i174;
import 'data/tag_management/repository/development_tag_management_repository.dart' as _i186;
import 'data/tag_management/repository/development_tag_repository.dart' as _i180;
import 'data/tag_management/repository/production_tag_management_repository.dart' as _i184;
import 'data/tag_management/repository/production_tag_repository.dart' as _i178;
import 'domain/achievement_management/repository/achievement_repository_interface.dart' as _i6;
import 'domain/achievement_management/repository/achievement_repository_mock.dart' as _i9;
import 'domain/achievement_management/use_case/award_achievement.dart' as _i18;
import 'domain/achievement_management/use_case/create_achievement.dart' as _i40;
import 'domain/achievement_management/use_case/delete_achievement.dart' as _i44;
import 'domain/achievement_management/use_case/edit_achievement.dart' as _i59;
import 'domain/achievement_management/use_case/get_achievement.dart' as _i92;
import 'domain/achievement_management/use_case/use_case_mocks.dart' as _i19;
import 'domain/achievement_management/use_case/watch_all_achievements.dart' as _i193;
import 'domain/authentication/repository/authentication_repository_interface.dart' as _i15;
import 'domain/authentication/repository/authentication_repository_mock.dart' as _i16;
import 'domain/authentication/use_case/get_logged_in_user.dart' as _i96;
import 'domain/authentication/use_case/log_in.dart' as _i111;
import 'domain/authentication/use_case/log_in_google.dart' as _i113;
import 'domain/authentication/use_case/log_out.dart' as _i114;
import 'domain/authentication/use_case/register.dart' as _i149;
import 'domain/authentication/use_case/use_case_mocks.dart' as _i97;
import 'domain/comments/repository/comment_repository_interface.dart' as _i32;
import 'domain/comments/repository/comment_repository_mock.dart' as _i33;
import 'domain/comments/use_case/delete_comment.dart' as _i47;
import 'domain/comments/use_case/edit_comment.dart' as _i60;
import 'domain/comments/use_case/post_comment.dart' as _i134;
import 'domain/comments/use_case/use_case_mocks.dart' as _i48;
import 'domain/comments/use_case/watch_experience_comments.dart' as _i196;
import 'domain/comments/use_case/watch_user_comments.dart' as _i219;
import 'domain/core/repository/core_repository_interface.dart' as _i36;
import 'domain/core/repository/core_repository_mock.dart' as _i39;
import 'domain/core/repository/geo_location_repository_interface.dart' as _i88;
import 'domain/core/repository/geo_location_repository_mock.dart' as _i89;
import 'domain/core/use_case/delete_cache.dart' as _i45;
import 'domain/core/use_case/get_current_location.dart' as _i94;
import 'domain/core/use_case/is_logged_in_user.dart' as _i102;
import 'domain/core/use_case/use_case.dart' as _i123;
import 'domain/core/use_case/use_case_mocks.dart' as _i46;
import 'domain/experience_log/repository/experience_log_repository_interface.dart' as _i70;
import 'domain/experience_log/repository/experience_log_repository_mock.dart' as _i71;
import 'domain/experience_log/use_case/add_experience_to_log.dart' as _i10;
import 'domain/experience_log/use_case/dismiss_experience_from_log.dart' as _i57;
import 'domain/experience_log/use_case/use_case_mocks.dart' as _i11;
import 'domain/experience_log/use_case/watch_user_log.dart' as _i221;
import 'domain/experience_management/repository/experience_management_repository_interface.dart' as _i76;
import 'domain/experience_management/repository/experience_management_repository_mock.dart' as _i78;
import 'domain/experience_management/use_case/create_experience.dart' as _i41;
import 'domain/experience_management/use_case/edit_experience.dart' as _i61;
import 'domain/experience_management/use_case/get_experience.dart' as _i95;
import 'domain/experience_management/use_case/use_case_mocks.dart' as _i42;
import 'domain/experience_navigation/repository/experience_navigation_repository_interface.dart' as _i79;
import 'domain/experience_navigation/repository/experience_navigation_repository_mock.dart' as _i81;
import 'domain/experience_navigation/use_case/dislike_experience.dart' as _i55;
import 'domain/experience_navigation/use_case/finish_experience.dart' as _i83;
import 'domain/experience_navigation/use_case/like_experience.dart' as _i103;
import 'domain/experience_navigation/use_case/load_surrounding_experiences.dart' as _i104;
import 'domain/experience_navigation/use_case/rate_difficulty.dart' as _i146;
import 'domain/experience_navigation/use_case/reward_user.dart' as _i157;
import 'domain/experience_navigation/use_case/use_case_mocks.dart' as _i56;
import 'domain/experience_navigation/use_case/watch_recommended_experiences.dart' as _i209;
import 'domain/main_feed/repository/main_feed_repository_interface.dart' as _i115;
import 'domain/main_feed/repository/main_feed_repository_mock.dart' as _i116;
import 'domain/main_feed/use_case/use_case_mocks.dart' as _i201;
import 'domain/main_feed/use_case/watch_feed.dart' as _i200;
import 'domain/notifications/repository/notification_repository_interface.dart' as _i125;
import 'domain/notifications/repository/notification_repository_mock.dart' as _i126;
import 'domain/notifications/use_case/check_notification.dart' as _i27;
import 'domain/notifications/use_case/delete_notification.dart' as _i50;
import 'domain/notifications/use_case/delete_user_notifications.dart' as _i54;
import 'domain/notifications/use_case/send_notification.dart' as _i170;
import 'domain/notifications/use_case/use_case_mocks.dart' as _i28;
import 'domain/notifications/use_case/watch_if_new_notifications.dart' as _i204;
import 'domain/notifications/use_case/watch_notifications.dart' as _i205;
import 'domain/options/repository/local_options_repository_interface.dart' as _i107;
import 'domain/options/repository/local_options_repository_mock.dart' as _i108;
import 'domain/options/repository/remote_options_repository_interface.dart' as _i151;
import 'domain/options/repository/remote_options_repository_mock.dart' as _i154;
import 'domain/options/use_case/delete_user.dart' as _i52;
import 'domain/options/use_case/save_global_options.dart' as _i159;
import 'domain/options/use_case/use_case_mocks.dart' as _i53;
import 'domain/profile/repository/profile_repository_interface.dart' as _i139;
import 'domain/profile/repository/profile_repository_mock.dart' as _i141;
import 'domain/profile/use_case/block_user.dart' as _i21;
import 'domain/profile/use_case/delete_experience.dart' as _i49;
import 'domain/profile/use_case/edit_user.dart' as _i63;
import 'domain/profile/use_case/follow_user.dart' as _i87;
import 'domain/profile/use_case/get_amout_of_followers.dart' as _i93;
import 'domain/profile/use_case/load_user.dart' as _i105;
import 'domain/profile/use_case/remove_experience_liked.dart' as _i155;
import 'domain/profile/use_case/un_block_user.dart' as _i189;
import 'domain/profile/use_case/un_follow_user.dart' as _i190;
import 'domain/profile/use_case/use_case_mocks.dart' as _i22;
import 'domain/profile/use_case/watch_blocked_users.dart' as _i195;
import 'domain/profile/use_case/watch_experiences_created.dart' as _i197;
import 'domain/profile/use_case/watch_experiences_done.dart' as _i198;
import 'domain/profile/use_case/watch_experiences_liked.dart' as _i199;
import 'domain/profile/use_case/watch_followed_users.dart' as _i202;
import 'domain/profile/use_case/watch_following_users.dart' as _i203;
import 'domain/profile/use_case/watch_user_achievements.dart' as _i218;
import 'domain/profile/use_case/watch_user_interests.dart' as _i220;
import 'domain/search/repository/search_repository_interface.dart' as _i164;
import 'domain/search/repository/search_repository_mock.dart' as _i165;
import 'domain/search/use_case/use_case_mocks.dart' as _i211;
import 'domain/search/use_case/watch_search_experiences_by_difficulty.dart' as _i210;
import 'domain/search/use_case/watch_search_experiences_by_name.dart' as _i212;
import 'domain/search/use_case/watch_search_experiences_by_tags.dart' as _i213;
import 'domain/search/use_case/watch_search_tags_by_name.dart' as _i214;
import 'domain/search/use_case/watch_search_users_by_name.dart' as _i215;
import 'domain/search/use_case/watch_search_users_by_username.dart' as _i216;
import 'domain/store/repository/store_repository_interface.dart' as _i172;
import 'domain/store/repository/store_repository_mock.dart' as _i173;
import 'domain/store/use_case/buy_coin.dart' as _i223;
import 'domain/store/use_case/buy_item.dart' as _i224;
import 'domain/store/use_case/buy_promotion_plan.dart' as _i225;
import 'domain/store/use_case/load_promotion_plans.dart' as _i230;
import 'domain/store/use_case/watch_owned_items.dart' as _i206;
import 'domain/store/use_case/watch_purchasable_items.dart' as _i207;
import 'domain/tag_management/repository/tag_management_repository_interface.dart' as _i183;
import 'domain/tag_management/repository/tag_management_repository_mock.dart' as _i185;
import 'domain/tag_management/repository/tag_repository_interface.dart' as _i177;
import 'domain/tag_management/repository/tag_repository_mock.dart' as _i179;
import 'domain/tag_management/use_case/add_tag_to_interests.dart' as _i12;
import 'domain/tag_management/use_case/create_tag.dart' as _i43;
import 'domain/tag_management/use_case/delete_tag.dart' as _i51;
import 'domain/tag_management/use_case/dismiss_tag_from_interests.dart' as _i58;
import 'domain/tag_management/use_case/edit_tag.dart' as _i62;
import 'domain/tag_management/use_case/get_tag.dart' as _i98;
import 'domain/tag_management/use_case/get_tag_creator.dart' as _i99;
import 'domain/tag_management/use_case/get_tags.dart' as _i100;
import 'domain/tag_management/use_case/use_case_mocks.dart' as _i13;
import 'domain/tag_management/use_case/watch_all_tags.dart' as _i194;
import 'domain/tag_management/use_case/watch_tags_by_creator.dart' as _i217;

const String _dev = 'dev';
const String _prod = 'prod';
const String _test = 'test';
// ignore_for_file: unnecessary_lambdas
// ignore_for_file: lines_longer_than_80_chars
/// initializes the registration of provided dependencies inside of [GetIt]
_i1.GetIt $initGetIt(_i1.GetIt get, {String? environment, _i2.EnvironmentFilter? environmentFilter}) {
  final gh = _i2.GetItHelper(get, environment, environmentFilter);
  final firebaseInjectableModule = _$FirebaseInjectableModule();
  gh.factory<_i3.AchievementManagementActorBloc>(() => _i3.AchievementManagementActorBloc());
  gh.factory<_i4.AchievementManagementFormBloc>(() => _i4.AchievementManagementFormBloc());
  gh.factory<_i5.AchievementManagementWatcherBloc>(() => _i5.AchievementManagementWatcherBloc());
  gh.lazySingleton<_i6.AchievementRepositoryInterface>(() => _i7.DevelopmentAchievementRepository(), registerFor: {_dev});
  gh.lazySingleton<_i6.AchievementRepositoryInterface>(() => _i8.ProductionAchievementRepository(), registerFor: {_prod});
  gh.lazySingleton<_i6.AchievementRepositoryInterface>(() => _i9.MockAchievementRepository(), registerFor: {_test});
  gh.lazySingleton<_i10.AddExperienceToLog>(() => _i11.MockAddExperienceToLog(), registerFor: {_test});
  gh.lazySingleton<_i12.AddTagToInterests>(() => _i13.MockAddTagToInterests(), registerFor: {_test});
  gh.factory<_i14.AuthenticationBloc>(() => _i14.AuthenticationBloc());
  gh.lazySingleton<_i15.AuthenticationRepositoryInterface>(() => _i16.MockAuthenticationRepository(), registerFor: {_test});
  gh.lazySingleton<_i15.AuthenticationRepositoryInterface>(() => _i17.DevelopmentAuthenticationRepository(), registerFor: {_dev});
  gh.lazySingleton<_i18.AwardAchievement>(() => _i18.AwardAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i18.AwardAchievement>(() => _i19.MockAwardAchievement(), registerFor: {_test});
  gh.factory<_i20.BlockActorBloc>(() => _i20.BlockActorBloc());
  gh.lazySingleton<_i21.BlockUser>(() => _i22.MockBlockUser(), registerFor: {_test});
  gh.factory<_i23.BlockedWatcherBloc>(() => _i23.BlockedWatcherBloc());
  gh.factory<_i24.BuyCoinsBloc>(() => _i24.BuyCoinsBloc());
  gh.factory<_i25.BuyItemBloc>(() => _i25.BuyItemBloc());
  gh.factory<_i26.BuyPromotionPlanActorBloc>(() => _i26.BuyPromotionPlanActorBloc());
  gh.lazySingleton<_i27.CheckNotification>(() => _i28.MockCheckNotification(), registerFor: {_test});
  gh.factory<_i29.CloudStorageService>(() => _i29.CloudStorageService());
  gh.factory<_i30.CommentActorBloc>(() => _i30.CommentActorBloc());
  gh.factory<_i31.CommentFormBloc>(() => _i31.CommentFormBloc());
  gh.lazySingleton<_i32.CommentRepositoryInterface>(() => _i33.MockCommentRepository(), registerFor: {_test});
  gh.lazySingleton<_i32.CommentRepositoryInterface>(() => _i34.DevelopmentCommentRepository(), registerFor: {_dev});
  gh.factory<_i35.CommentWatcherBloc>(() => _i35.CommentWatcherBloc());
  gh.lazySingleton<_i36.CoreRepositoryInterface>(() => _i37.DevelopmentCoreRepository(), registerFor: {_dev});
  gh.lazySingleton<_i36.CoreRepositoryInterface>(() => _i38.ProductionCoreRepository(), registerFor: {_prod});
  gh.lazySingleton<_i36.CoreRepositoryInterface>(() => _i39.MockCoreRepository(), registerFor: {_test});
  gh.lazySingleton<_i40.CreateAchievement>(() => _i40.CreateAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i40.CreateAchievement>(() => _i19.MockCreateAchievement(), registerFor: {_test});
  gh.lazySingleton<_i41.CreateExperience>(() => _i42.MockCreateExperience(), registerFor: {_test});
  gh.lazySingleton<_i43.CreateTag>(() => _i13.MockCreateTag(), registerFor: {_test});
  gh.lazySingleton<_i44.DeleteAchievement>(() => _i44.DeleteAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i44.DeleteAchievement>(() => _i19.MockDeleteAchievement(), registerFor: {_test});
  gh.lazySingleton<_i45.DeleteCache>(() => _i46.MockDeleteCache(), registerFor: {_test});
  gh.lazySingleton<_i45.DeleteCache>(() => _i45.DeleteCache(get<_i36.CoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i47.DeleteComment>(() => _i48.MockDeleteComment(), registerFor: {_test});
  gh.lazySingleton<_i47.DeleteComment>(() => _i47.DeleteComment(get<_i32.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i49.DeleteExperience>(() => _i22.MockDeleteExperience(), registerFor: {_test});
  gh.lazySingleton<_i50.DeleteNotification>(() => _i28.MockDeleteNotification(), registerFor: {_test});
  gh.lazySingleton<_i51.DeleteTag>(() => _i13.MockDeleteTag(), registerFor: {_test});
  gh.lazySingleton<_i52.DeleteUser>(() => _i53.MockDeleteUser(), registerFor: {_test});
  gh.lazySingleton<_i54.DeleteUserNotifications>(() => _i28.MockDeleteUserNotifications(), registerFor: {_test});
  gh.lazySingleton<_i55.DislikeExperience>(() => _i56.MockDislikeExperience(), registerFor: {_test});
  gh.lazySingleton<_i57.DismissExperienceFromLog>(() => _i11.MockDismissExperienceFromLog(), registerFor: {_test});
  gh.lazySingleton<_i58.DismissTagFromInterests>(() => _i13.MockDismissTagFromInterests(), registerFor: {_test});
  gh.lazySingleton<_i59.EditAchievement>(() => _i59.EditAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i59.EditAchievement>(() => _i19.MockEditAchievement(), registerFor: {_test});
  gh.lazySingleton<_i60.EditComment>(() => _i48.MockEditComment(), registerFor: {_test});
  gh.lazySingleton<_i60.EditComment>(() => _i60.EditComment(get<_i32.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i61.EditExperience>(() => _i42.MockEditExperience(), registerFor: {_test});
  gh.lazySingleton<_i62.EditTag>(() => _i13.MockEditTag(), registerFor: {_test});
  gh.lazySingleton<_i63.EditUser>(() => _i22.MockEditUser(), registerFor: {_test});
  gh.factory<_i64.ExperienceCardActorBloc>(() => _i64.ExperienceCardActorBloc());
  gh.factory<_i65.ExperienceCardLikeCheckBloc>(() => _i65.ExperienceCardLikeCheckBloc());
  gh.factory<_i66.ExperienceEditingFormBloc>(() => _i66.ExperienceEditingFormBloc());
  gh.factory<_i67.ExperienceFinishActorBloc>(() => _i67.ExperienceFinishActorBloc());
  gh.factory<_i68.ExperienceLikeActorBloc>(() => _i68.ExperienceLikeActorBloc());
  gh.factory<_i69.ExperienceLogActorBloc>(() => _i69.ExperienceLogActorBloc());
  gh.lazySingleton<_i70.ExperienceLogRepositoryInterface>(() => _i71.MockExperienceLogRepository(), registerFor: {_test});
  gh.lazySingleton<_i70.ExperienceLogRepositoryInterface>(() => _i72.DevelopmentExperienceLogRepository(), registerFor: {_dev});
  gh.factory<_i73.ExperienceLogWatcherBloc>(() => _i73.ExperienceLogWatcherBloc());
  gh.factory<_i74.ExperienceManagementActorBloc>(() => _i74.ExperienceManagementActorBloc());
  gh.factory<_i75.ExperienceManagementFormBloc>(() => _i75.ExperienceManagementFormBloc());
  gh.lazySingleton<_i76.ExperienceManagementRepositoryInterface>(() => _i77.DevelopmentExperienceManagementRepository(), registerFor: {_dev});
  gh.lazySingleton<_i76.ExperienceManagementRepositoryInterface>(() => _i78.MockExperienceManagementRepository(), registerFor: {_test});
  gh.lazySingleton<_i79.ExperienceNavigationRepositoryInterface>(() => _i80.DevelopmentExperienceNavigationRepository(), registerFor: {_dev});
  gh.lazySingleton<_i79.ExperienceNavigationRepositoryInterface>(() => _i81.MockExperienceNavigationRepository(), registerFor: {_test});
  gh.factory<_i82.ExperienceNavigationWatcherBloc>(() => _i82.ExperienceNavigationWatcherBloc());
  gh.lazySingleton<_i83.FinishExperience>(() => _i83.FinishExperience(get<_i79.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i83.FinishExperience>(() => _i56.MockFinishExperience(), registerFor: {_test});
  gh.lazySingleton<_i84.FirebaseAuth>(() => firebaseInjectableModule.firebaseAuth);
  gh.lazySingleton<_i85.FirebaseFirestore>(() => firebaseInjectableModule.firestore);
  gh.factory<_i86.FollowActorBloc>(() => _i86.FollowActorBloc());
  gh.lazySingleton<_i87.FollowUser>(() => _i22.MockFollowUser(), registerFor: {_test});
  gh.lazySingleton<_i88.GeoLocationRepositoryInterface>(() => _i89.MockGeoLocationRepository(), registerFor: {_test});
  gh.lazySingleton<_i88.GeoLocationRepositoryInterface>(() => _i90.DevelopmentGeoLocationRepository(), registerFor: {_dev});
  gh.lazySingleton<_i88.GeoLocationRepositoryInterface>(() => _i91.ProductionGeoLocationRepository(), registerFor: {_prod});
  gh.lazySingleton<_i92.GetAchievement>(() => _i19.MockGetAchievement(), registerFor: {_test});
  gh.lazySingleton<_i92.GetAchievement>(() => _i92.GetAchievement(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i93.GetAmountOfFollowers>(() => _i22.MockGetAmountOfFollowers(), registerFor: {_test});
  gh.lazySingleton<_i94.GetCurrentLocation>(() => _i94.GetCurrentLocation(get<_i88.GeoLocationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i94.GetCurrentLocation>(() => _i46.MockGetCurrentLocation(), registerFor: {_test});
  gh.lazySingleton<_i95.GetExperience>(() => _i42.MockGetExperience(), registerFor: {_test});
  gh.lazySingleton<_i95.GetExperience>(() => _i95.GetExperience(get<_i76.ExperienceManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i96.GetLoggedInUser>(() => _i96.GetLoggedInUser(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i96.GetLoggedInUser>(() => _i97.MockGetLoggedInUser(), registerFor: {_test});
  gh.lazySingleton<_i98.GetTag>(() => _i13.MockGetTag(), registerFor: {_test});
  gh.lazySingleton<_i99.GetTagCreator>(() => _i13.MockGetTagCreator(), registerFor: {_test});
  gh.lazySingleton<_i100.GetTags>(() => _i13.MockGetTags(), registerFor: {_test});
  gh.lazySingleton<_i101.GoogleSignIn>(() => firebaseInjectableModule.googleSignIn);
  gh.lazySingleton<_i102.IsLoggedInUser>(() => _i102.IsLoggedInUser(), registerFor: {_dev, _prod});
  gh.lazySingleton<_i102.IsLoggedInUser>(() => _i46.MockIsLoggedInUser(), registerFor: {_test});
  gh.lazySingleton<_i103.LikeExperience>(() => _i56.MockLikeExperience(), registerFor: {_test});
  gh.lazySingleton<_i103.LikeExperience>(() => _i103.LikeExperience(get<_i79.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i104.LoadSurroundingExperiences>(() => _i104.LoadSurroundingExperiences(get<_i79.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i104.LoadSurroundingExperiences>(() => _i56.MockLoadSurroundingExperiences(), registerFor: {_test});
  gh.lazySingleton<_i105.LoadUser>(() => _i22.MockLoadUser(), registerFor: {_test});
  gh.factory<_i106.LoadUserBloc>(() => _i106.LoadUserBloc());
  gh.lazySingleton<_i107.LocalOptionsRepositoryInterface>(() => _i108.MockLocalOptionsRepository(), registerFor: {_test});
  gh.lazySingleton<_i107.LocalOptionsRepositoryInterface>(() => _i109.DevelopmentLocalOptionsRepository(), registerFor: {_dev});
  gh.lazySingleton<_i107.LocalOptionsRepositoryInterface>(() => _i110.ProductionLocalOptionsRepository(), registerFor: {_prod});
  gh.lazySingleton<_i111.LogIn>(() => _i111.LogIn(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i111.LogIn>(() => _i97.MockLogIn(), registerFor: {_test});
  gh.factory<_i112.LogInFormBloc>(() => _i112.LogInFormBloc());
  gh.lazySingleton<_i113.LogInGoogle>(() => _i113.LogInGoogle(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i113.LogInGoogle>(() => _i97.MockLogInGoogle(), registerFor: {_test});
  gh.lazySingleton<_i114.LogOut>(() => _i114.LogOut(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i114.LogOut>(() => _i97.MockLogOut(), registerFor: {_test});
  gh.lazySingleton<_i115.MainFeedRepositoryInterface>(() => _i116.MockMainFeedRepository(), registerFor: {_test});
  gh.lazySingleton<_i115.MainFeedRepositoryInterface>(() => _i117.DevelopmentMainFeedRepository(), registerFor: {_dev});
  gh.lazySingleton<_i115.MainFeedRepositoryInterface>(() => _i118.ProductionMainFeedRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.factory<_i119.MainFeedWatcherBloc>(() => _i119.MainFeedWatcherBloc());
  gh.factory<_i120.MapControllerBloc>(() => _i120.MapControllerBloc());
  gh.factory<_i121.NavigationActorBloc>(() => _i121.NavigationActorBloc());
  gh.factory<_i122.NewNotificationsWatcherBloc>(() => _i122.NewNotificationsWatcherBloc());
  gh.lazySingleton<_i123.NoParams>(() => _i123.NoParams());
  gh.factory<_i124.NotificationActorBloc>(() => _i124.NotificationActorBloc());
  gh.lazySingleton<_i125.NotificationRepositoryInterface>(() => _i126.MockNotificationRepository(), registerFor: {_test});
  gh.lazySingleton<_i125.NotificationRepositoryInterface>(() => _i127.DevelopmentNotificationRepository(), registerFor: {_dev});
  gh.lazySingleton<_i125.NotificationRepositoryInterface>(() => _i128.ProductionNotificationRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.factory<_i129.NotificationsWatcherBloc>(() => _i129.NotificationsWatcherBloc());
  gh.factory<_i130.ObjectiveFormBloc>(() => _i130.ObjectiveFormBloc());
  gh.factory<_i131.ObjectivesCreationBloc>(() => _i131.ObjectivesCreationBloc());
  gh.factory<_i132.ObjectivesTrackerBloc>(() => _i132.ObjectivesTrackerBloc());
  gh.factory<_i133.OptionsFormBloc>(() => _i133.OptionsFormBloc());
  gh.lazySingleton<_i134.PostComment>(() => _i48.MockPostComment(), registerFor: {_test});
  gh.lazySingleton<_i134.PostComment>(() => _i134.PostComment(get<_i32.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.factory<_i135.ProfileAchievementsWatcherBloc>(() => _i135.ProfileAchievementsWatcherBloc());
  gh.factory<_i136.ProfileEditingFormBloc>(() => _i136.ProfileEditingFormBloc());
  gh.factory<_i137.ProfileExperiencesWatcherBloc>(() => _i137.ProfileExperiencesWatcherBloc());
  gh.factory<_i138.ProfileInterestsWatcherBloc>(() => _i138.ProfileInterestsWatcherBloc());
  gh.lazySingleton<_i139.ProfileRepositoryInterface>(() => _i140.ProductionProfileRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i139.ProfileRepositoryInterface>(() => _i141.MockProfileRepository(), registerFor: {_test});
  gh.lazySingleton<_i139.ProfileRepositoryInterface>(() => _i142.DevelopmentProfileRepository(), registerFor: {_dev});
  gh.factory<_i143.ProfileUsersWatcherBloc>(() => _i143.ProfileUsersWatcherBloc());
  gh.factory<_i144.ProfileWatcherBloc>(() => _i144.ProfileWatcherBloc());
  gh.factory<_i145.PromotionPlansLoaderBloc>(() => _i145.PromotionPlansLoaderBloc());
  gh.lazySingleton<_i146.RateDifficulty>(() => _i146.RateDifficulty(get<_i79.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i146.RateDifficulty>(() => _i56.MockRateDifficulty(), registerFor: {_test});
  gh.factory<_i147.RateExperienceDifficultyActorBloc>(() => _i147.RateExperienceDifficultyActorBloc());
  gh.factory<_i148.RecommendedExperiencesWatcherBloc>(() => _i148.RecommendedExperiencesWatcherBloc());
  gh.lazySingleton<_i149.Register>(() => _i97.MockRegister(), registerFor: {_test});
  gh.lazySingleton<_i149.Register>(() => _i149.Register(get<_i15.AuthenticationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.factory<_i150.RegistrationFormBloc>(() => _i150.RegistrationFormBloc());
  gh.lazySingleton<_i151.RemoteOptionsRepositoryInterface>(() => _i152.ProductionRemoteOptionsRepository(), registerFor: {_prod});
  gh.lazySingleton<_i151.RemoteOptionsRepositoryInterface>(() => _i153.DevelopmentRemoteOptionsRepository(), registerFor: {_dev});
  gh.lazySingleton<_i151.RemoteOptionsRepositoryInterface>(() => _i154.MockRemoteOptionsRepository(), registerFor: {_test});
  gh.lazySingleton<_i155.RemoveExperienceLiked>(() => _i155.RemoveExperienceLiked(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i155.RemoveExperienceLiked>(() => _i22.MockRemoveExperienceLiked(), registerFor: {_test});
  gh.factory<_i156.RewardFormBloc>(() => _i156.RewardFormBloc());
  gh.lazySingleton<_i157.RewardUser>(() => _i157.RewardUser(get<_i79.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i157.RewardUser>(() => _i56.MockRewardUser(), registerFor: {_test});
  gh.factory<_i158.RewardsCreationBloc>(() => _i158.RewardsCreationBloc());
  gh.lazySingleton<_i159.SaveGlobalOptions>(() => _i53.MockSaveGlobalOptions(), registerFor: {_test});
  gh.lazySingleton<_i159.SaveGlobalOptions>(() => _i159.SaveGlobalOptions(get<_i151.RemoteOptionsRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.factory<_i160.SearchByNameFormBloc>(() => _i160.SearchByNameFormBloc());
  gh.factory<_i161.SearchExperiencesByDifficultyBloc>(() => _i161.SearchExperiencesByDifficultyBloc());
  gh.factory<_i162.SearchExperiencesByNameWatcherBloc>(() => _i162.SearchExperiencesByNameWatcherBloc());
  gh.factory<_i163.SearchExperiencesByTagsBloc>(() => _i163.SearchExperiencesByTagsBloc());
  gh.lazySingleton<_i164.SearchRepositoryInterface>(() => _i165.MockSearchRepository(), registerFor: {_test});
  gh.lazySingleton<_i164.SearchRepositoryInterface>(() => _i166.ProductionSearchRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i164.SearchRepositoryInterface>(() => _i167.DevelopmentSearchRepository(), registerFor: {_dev});
  gh.factory<_i168.SearchTagsByNameWatcherBloc>(() => _i168.SearchTagsByNameWatcherBloc());
  gh.factory<_i169.SearchUsersByNameWatcherBloc>(() => _i169.SearchUsersByNameWatcherBloc());
  gh.lazySingleton<_i170.SendNotification>(() => _i28.MockSendNotification(), registerFor: {_test});
  gh.lazySingleton<_i170.SendNotification>(() => _i170.SendNotification(get<_i125.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.factory<_i171.StoreNavigationActorBloc>(() => _i171.StoreNavigationActorBloc());
  gh.lazySingleton<_i172.StoreRepositoryInterface>(() => _i173.MockStoreRepository(), registerFor: {_test});
  gh.lazySingleton<_i172.StoreRepositoryInterface>(() => _i174.ProductionStoreRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i172.StoreRepositoryInterface>(() => _i175.DevelopmentStoreRepository(), registerFor: {_dev});
  gh.factory<_i176.TagCardActorBloc>(() => _i176.TagCardActorBloc());
  gh.lazySingleton<_i177.TagCoreRepositoryInterface>(() => _i178.ProductionTagRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i177.TagCoreRepositoryInterface>(() => _i179.MockTagRepository(), registerFor: {_test});
  gh.lazySingleton<_i177.TagCoreRepositoryInterface>(() => _i180.DevelopmentTagRepository(), registerFor: {_dev});
  gh.factory<_i181.TagManagementActorBloc>(() => _i181.TagManagementActorBloc());
  gh.factory<_i182.TagManagementFormBloc>(() => _i182.TagManagementFormBloc());
  gh.lazySingleton<_i183.TagManagementRepositoryInterface>(() => _i184.ProductionTagManagementRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i183.TagManagementRepositoryInterface>(() => _i185.MockTagManagementRepository(), registerFor: {_test});
  gh.lazySingleton<_i183.TagManagementRepositoryInterface>(() => _i186.DevelopmentTagManagementRepository(), registerFor: {_dev});
  gh.factory<_i187.TagManagementWatcherBloc>(() => _i187.TagManagementWatcherBloc());
  gh.factory<_i188.TagSelectorBloc>(() => _i188.TagSelectorBloc());
  gh.lazySingleton<_i189.UnBlockUser>(() => _i189.UnBlockUser(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i189.UnBlockUser>(() => _i22.MockUnBlockUser(), registerFor: {_test});
  gh.lazySingleton<_i190.UnFollowUser>(() => _i190.UnFollowUser(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i190.UnFollowUser>(() => _i22.MockUnFollowUser(), registerFor: {_test});
  gh.factory<_i191.UserActorBloc>(() => _i191.UserActorBloc());
  gh.factory<_i192.UserProfileButtonWatcherBloc>(() => _i192.UserProfileButtonWatcherBloc());
  gh.lazySingleton<_i193.WatchAllAchievements>(() => _i19.MockGetAllAchievements(), registerFor: {_test});
  gh.lazySingleton<_i193.WatchAllAchievements>(() => _i193.WatchAllAchievements(get<_i6.AchievementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i194.WatchAllTags>(() => _i13.MockGetAllTags(), registerFor: {_test});
  gh.lazySingleton<_i194.WatchAllTags>(() => _i194.WatchAllTags(get<_i177.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i195.WatchBlockedUsers>(() => _i22.MockLoadBlockedUsers(), registerFor: {_test});
  gh.lazySingleton<_i195.WatchBlockedUsers>(() => _i195.WatchBlockedUsers(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i196.WatchExperienceComments>(() => _i196.WatchExperienceComments(get<_i32.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i196.WatchExperienceComments>(() => _i48.MockGetExperienceComments(), registerFor: {_test});
  gh.lazySingleton<_i197.WatchExperiencesCreated>(() => _i22.MockLoadExperiencesCreated(), registerFor: {_test});
  gh.lazySingleton<_i197.WatchExperiencesCreated>(() => _i197.WatchExperiencesCreated(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i198.WatchExperiencesDone>(() => _i22.MockLoadExperiencesDone(), registerFor: {_test});
  gh.lazySingleton<_i198.WatchExperiencesDone>(() => _i198.WatchExperiencesDone(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i199.WatchExperiencesLiked>(() => _i22.MockLoadExperiencesLiked(), registerFor: {_test});
  gh.lazySingleton<_i199.WatchExperiencesLiked>(() => _i199.WatchExperiencesLiked(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i200.WatchFeed>(() => _i200.WatchFeed(get<_i115.MainFeedRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i200.WatchFeed>(() => _i201.MockFillFeed(), registerFor: {_test});
  gh.lazySingleton<_i202.WatchFollowedUsers>(() => _i202.WatchFollowedUsers(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i202.WatchFollowedUsers>(() => _i22.MockLoadFollowedUsers(), registerFor: {_test});
  gh.lazySingleton<_i203.WatchFollowingUsers>(() => _i203.WatchFollowingUsers(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i203.WatchFollowingUsers>(() => _i22.MockLoadFollowingUsers(), registerFor: {_test});
  gh.lazySingleton<_i204.WatchIfNewNotifications>(() => _i204.WatchIfNewNotifications(get<_i125.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i205.WatchNotifications>(() => _i205.WatchNotifications(get<_i125.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i205.WatchNotifications>(() => _i28.MockLoadNotifications(), registerFor: {_test});
  gh.lazySingleton<_i206.WatchOwnedItems>(() => _i206.WatchOwnedItems(get<_i172.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i207.WatchPurchasableItems>(() => _i207.WatchPurchasableItems(get<_i172.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.factory<_i208.WatchPurchasableItemsBloc>(() => _i208.WatchPurchasableItemsBloc());
  gh.lazySingleton<_i209.WatchRecommendedExperiences>(() => _i209.WatchRecommendedExperiences(get<_i79.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i210.WatchSearchExperiencesByDifficulty>(() => _i211.MockSearchExperiencesByDifficulty(), registerFor: {_test});
  gh.lazySingleton<_i210.WatchSearchExperiencesByDifficulty>(() => _i210.WatchSearchExperiencesByDifficulty(get<_i164.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i212.WatchSearchExperiencesByName>(() => _i211.MockSearchExperiencesByName(), registerFor: {_test});
  gh.lazySingleton<_i212.WatchSearchExperiencesByName>(() => _i212.WatchSearchExperiencesByName(get<_i164.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i213.WatchSearchExperiencesByTags>(() => _i211.MockSearchExperiencesByTags(), registerFor: {_test});
  gh.lazySingleton<_i213.WatchSearchExperiencesByTags>(() => _i213.WatchSearchExperiencesByTags(get<_i164.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i214.WatchSearchTagsByName>(() => _i214.WatchSearchTagsByName(get<_i164.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i214.WatchSearchTagsByName>(() => _i211.MockSearchTagsByName(), registerFor: {_test});
  gh.lazySingleton<_i215.WatchSearchUsersByName>(() => _i215.WatchSearchUsersByName(get<_i164.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i215.WatchSearchUsersByName>(() => _i211.MockSearchUsersByName(), registerFor: {_test});
  gh.lazySingleton<_i216.WatchSearchUsersByUsername>(() => _i211.MockSearchUsersByUsername(), registerFor: {_test});
  gh.lazySingleton<_i216.WatchSearchUsersByUsername>(() => _i216.WatchSearchUsersByUsername(get<_i164.SearchRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i217.WatchTagsByCreator>(() => _i13.MockGetTagsByCreator(), registerFor: {_test});
  gh.lazySingleton<_i217.WatchTagsByCreator>(() => _i217.WatchTagsByCreator(get<_i177.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i218.WatchUserAchievements>(() => _i218.WatchUserAchievements(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i218.WatchUserAchievements>(() => _i22.MockLoadUserAchievements(), registerFor: {_test});
  gh.lazySingleton<_i219.WatchUserComments>(() => _i48.MockGetUserComments(), registerFor: {_test});
  gh.lazySingleton<_i219.WatchUserComments>(() => _i219.WatchUserComments(get<_i32.CommentRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i220.WatchUserInterests>(() => _i220.WatchUserInterests(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i220.WatchUserInterests>(() => _i22.MockLoadUserInterests(), registerFor: {_test});
  gh.lazySingleton<_i221.WatchUserLog>(() => _i11.MockLoadUserLog(), registerFor: {_test});
  gh.lazySingleton<_i221.WatchUserLog>(() => _i221.WatchUserLog(get<_i70.ExperienceLogRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i10.AddExperienceToLog>(() => _i10.AddExperienceToLog(get<_i70.ExperienceLogRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i12.AddTagToInterests>(() => _i12.AddTagToInterests(get<_i177.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i15.AuthenticationRepositoryInterface>(() => _i222.ProductionAuthenticationRepository(get<_i84.FirebaseAuth>(), get<_i101.GoogleSignIn>(), get<_i85.FirebaseFirestore>()),
      registerFor: {_prod});
  gh.lazySingleton<_i21.BlockUser>(() => _i21.BlockUser(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i223.BuyCoins>(() => _i223.BuyCoins(get<_i172.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i224.BuyItem>(() => _i224.BuyItem(get<_i172.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i225.BuyPromotionPlan>(() => _i225.BuyPromotionPlan(get<_i172.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i27.CheckNotification>(() => _i27.CheckNotification(get<_i125.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i32.CommentRepositoryInterface>(() => _i226.ProductionCommentRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i41.CreateExperience>(() => _i41.CreateExperience(get<_i76.ExperienceManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i43.CreateTag>(() => _i43.CreateTag(get<_i183.TagManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i49.DeleteExperience>(() => _i49.DeleteExperience(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i50.DeleteNotification>(() => _i50.DeleteNotification(get<_i125.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i51.DeleteTag>(() => _i51.DeleteTag(get<_i183.TagManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i52.DeleteUser>(() => _i52.DeleteUser(get<_i151.RemoteOptionsRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i54.DeleteUserNotifications>(() => _i54.DeleteUserNotifications(get<_i125.NotificationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i55.DislikeExperience>(() => _i55.DislikeExperience(get<_i79.ExperienceNavigationRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i57.DismissExperienceFromLog>(() => _i57.DismissExperienceFromLog(get<_i70.ExperienceLogRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i58.DismissTagFromInterests>(() => _i58.DismissTagFromInterests(get<_i177.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i61.EditExperience>(() => _i61.EditExperience(get<_i76.ExperienceManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i62.EditTag>(() => _i62.EditTag(get<_i183.TagManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i63.EditUser>(() => _i63.EditUser(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i70.ExperienceLogRepositoryInterface>(() => _i227.ProductionExperienceLogRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i76.ExperienceManagementRepositoryInterface>(() => _i228.ProductionExperienceManagementRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i79.ExperienceNavigationRepositoryInterface>(() => _i229.ProductionExperienceNavigationRepository(get<_i85.FirebaseFirestore>()), registerFor: {_prod});
  gh.lazySingleton<_i87.FollowUser>(() => _i87.FollowUser(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i93.GetAmountOfFollowers>(() => _i93.GetAmountOfFollowers(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i98.GetTag>(() => _i98.GetTag(get<_i183.TagManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i99.GetTagCreator>(() => _i99.GetTagCreator(get<_i177.TagCoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i100.GetTags>(() => _i100.GetTags(get<_i183.TagManagementRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i230.LoadPromotionPlans>(() => _i230.LoadPromotionPlans(get<_i172.StoreRepositoryInterface>()), registerFor: {_dev, _prod});
  gh.lazySingleton<_i105.LoadUser>(() => _i105.LoadUser(get<_i139.ProfileRepositoryInterface>()), registerFor: {_dev, _prod});
  return get;
}

class _$FirebaseInjectableModule extends _i231.FirebaseInjectableModule {}
